### ISSUE TITLE
Flowblade crashes on start after switching from two connected monitors to one

### ISSUE THREAD

**Issue by mikerofone** [jliljebl/flowblade#1007]
**Please include the following information.**
1) Flowblade version: v2.8
2) MLT version: 6.20.0
3) Your distribution (Ubuntu, Debian, Mint etc.): Linux Mint 20.1 Cinnamon

**Reproduction:**
1. Have two monitors A and B enabled on desktop environment.
2. Start Flowblade.
3. In `Preferences` --> `View`, select monitor A for `Do GUI layout based on:`.
3. Close Flowblade.
4. Disable monitor B, so only A is left.
5. Start Flowblade again.

**Expected:**
Flowblade starts, rendering on monitor A.

**Actual:**
Crashes on startup while trying to recover settings for a monitor that no longer exists (?).

```
$ flowblade
FLOWBLADE MOVIE EDITOR 2.8
--------------------------
Launch script dir: /usr/bin
Running from installation...
modules path: /usr/share/flowblade/Flowblade
MLT found, version: 6.20.0
numpy version: 1.17.4
Application version: 2.8.0
OS: Linux Mint 20.1
Python 3.8.5 (default, Jan 27 2021, 15:41:15) 
[GCC 9.3.0]
GTK+ version: 3.24.20
XDG user data exists.
Locale: en_US
Translations at /usr/share/locale were not found, using program root directory translations.
Use OS locale language.
Valid shortcut files found: ['flowblade.xml', 'premiere.xml']
Keyboard shortcuts file: flowblade.xml
Gtk version is 3.24.20, Flowblade theme is available.
Traceback (most recent call last):
  File "/usr/bin/flowblade", line 93, in <module>
    app.main(modules_path)
  File "/usr/share/flowblade/Flowblade/app.py", line 247, in main
    scr_w, scr_h = _set_screen_size_data()
  File "/usr/share/flowblade/Flowblade/app.py", line 917, in _set_screen_size_data
    scr_w, scr_h = monitor_data[monitor_data_index]
IndexError: list index out of range
```

Starts fine after re-enabling second monitor.

**Workaround**

In `Preferences` --> `View`, select "Full display area" for `Do GUI layout based on:`.

**Additional information**

* I have three displays connected to my computer, two via HDMI (monitors B and C) and one via DP (monitor A in the repro steps). The DP one is my "main" display, and the others are normally turned off.
* I yesterday started using Flowblade with A and B enabled, and only intend to use Flowblade on monitor A. That's why I've chosen that one in the preferences, though I don't know why it really matters.
* `xrandr` output with **working** screen configuration (one HDMI, one DP enabled):
    ```$ xrandr
    Screen 0: minimum 8 x 8, current 4480 x 2520, maximum 32767 x 32767
    DVI-D-0 disconnected (normal left inverted right x axis y axis)
    HDMI-0 connected 1920x1080+0+0 (normal left inverted right x axis y axis) 531mm x 299mm
       1920x1080     60.00*+
       1680x1050     59.95  
       1440x900      59.89  
       1280x1024     75.02    60.02  
       1280x960      60.00  
       1280x720      60.00  
       1024x768      75.03    70.07    60.00  
       800x600       75.00    72.19    60.32    56.25  
       640x480       75.00    72.81    59.94  
    HDMI-1 connected (normal left inverted right x axis y axis)
       1920x1080     60.00 +  59.94    50.00    60.05    60.00    50.04  
       1680x1050     59.95  
       1280x1024     75.02    60.02  
       1280x960      60.00  
       1280x720      60.00    59.94    50.00  
       1152x864      75.00  
       1024x768      75.03    60.00  
       800x600       75.00    60.32    56.25  
       720x576       50.00  
       720x480       59.94  
       640x480       75.00    59.93    59.94  
    DP-0 connected primary 2560x1440+1920+1080 (normal left inverted right x axis y axis) 597mm x 336mm
       2560x1440     59.95*+
       1920x1080     60.00    59.94    50.00  
       1680x1050     59.95  
       1440x900      59.89  
       1280x1440     59.91  
       1280x1024     75.02    60.02  
       1280x960      60.00  
       1280x720      60.00    59.94    50.00  
       1024x768      75.03    70.07    60.00  
       800x600       75.00    72.19    60.32    56.25  
       720x576       50.00  
       720x480       59.94  
       640x480       75.00    72.81    59.93    59.94  
    DP-1 disconnected (normal left inverted right x axis y axis)
    DP-2 disconnected (normal left inverted right x axis y axis)
    DP-3 disconnected (normal left inverted right x axis y axis)
    ```
* `xrandr` output with **crashing** screen configuration (only DP screen enabled):
    ```
    Screen 0: minimum 8 x 8, current 2560 x 1440, maximum 32767 x 32767
    DVI-D-0 disconnected (normal left inverted right x axis y axis)
    HDMI-0 connected (normal left inverted right x axis y axis)
       1920x1080     60.00 +
       1680x1050     59.95  
       1440x900      59.89  
       1280x1024     75.02    60.02  
       1280x960      60.00  
       1280x720      60.00  
       1024x768      75.03    70.07    60.00  
       800x600       75.00    72.19    60.32    56.25  
       640x480       75.00    72.81    59.94  
    HDMI-1 connected (normal left inverted right x axis y axis)
       1920x1080     60.00 +  59.94    50.00    60.05    60.00    50.04  
       1680x1050     59.95  
       1280x1024     75.02    60.02  
       1280x960      60.00  
       1280x720      60.00    59.94    50.00  
       1152x864      75.00  
       1024x768      75.03    60.00  
       800x600       75.00    60.32    56.25  
       720x576       50.00  
       720x480       59.94  
       640x480       75.00    59.93    59.94  
    DP-0 connected primary 2560x1440+0+0 (normal left inverted right x axis y axis) 597mm x 336mm
       2560x1440     59.95*+
       1920x1080     60.00    59.94    50.00  
       1680x1050     59.95  
       1440x900      59.89  
       1280x1440     59.91  
       1280x1024     75.02    60.02  
       1280x960      60.00  
       1280x720      60.00    59.94    50.00  
       1024x768      75.03    70.07    60.00  
       800x600       75.00    72.19    60.32    56.25  
       720x576       50.00  
       720x480       59.94  
       640x480       75.00    72.81    59.93    59.94  
    DP-1 disconnected (normal left inverted right x axis y axis)
    DP-2 disconnected (normal left inverted right x axis y axis)
    DP-3 disconnected (normal left inverted right x axis y axis)
    ```

**Comment by mikerofone** [comment]
FYI I've edited the initial report after poking around some more, and I now have reliable repro steps and a workaround.

It seems like what's missing is a graceful fallback to "Full display area" if the monitor configuration has changed, or an alternate way of identifying which monitor is which that is independent of display ordering.

**Comment by jliljebl** [comment]
Thanks. Your description of the Issue seems correct and we can probably fix this with one *try...except*  around line   *scr_w, scr_h = monitor_data[monitor_data_index]* that resets some prefs if we get error on that line.

**Comment by jliljebl** [comment]
Fixed in repo. I had code to handle this case but it was clearly written without plugging two monitors in and actually doing a test.

**Comment by mikerofone** [comment]
Cool, thanks for the fix! :)
