### ISSUE TITLE
Error when using undo

### ISSUE THREAD

**Issue by Mec-iS** [jliljebl/flowblade#1080]
When trying to undo the action is not undone, this is the error displayed in Ubuntu crash log:
```
Traceback:
 Traceback (most recent call last):
   File "/usr/share/flowblade/Flowblade/undo.py", line 88, in do_undo_and_repaint
     do_undo()
   File "/usr/share/flowblade/Flowblade/undo.py", line 112, in do_undo
     undo_edit.undo()
   File "/usr/share/flowblade/Flowblade/edit.py", line 380, in undo
     self.undo_func(self)
   File "/usr/share/flowblade/Flowblade/edit.py", line 1791, in _add_filter_undo
     self.filter_edit_done_func(self.clip, len(self.clip.filters) - 1) # updates effect stack gui
   File "/usr/share/flowblade/Flowblade/clipeffectseditor.py", line 782, in filter_edit_done_stack_update
     update_stack()
 TypeError: update_stack() missing 3 required positional arguments: 'clip', 'track', and 'clip_index'
```

These are the system specs:
```
FLOWBLADE MOVIE EDITOR 2.8
--------------------------
Launch script dir: /usr/bin
Running from installation...
modules path: /usr/share/flowblade/Flowblade
MLT found, version: 7.4.0
numpy version: 1.21.5
Application version: 2.8.0
OS: Ubuntu 22.04.1 LTS
Python 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0]
GTK+ version: 3.24.33
```

**Comment by jliljebl** [comment]
This is fixed in repo.
