### ISSUE TITLE
Crashes on startup with AttributeError: 'NoneType' object has no attribute 'set_size_request'

### ISSUE THREAD

**Issue by Wolfyxon** [jliljebl/flowblade#1095]
1) Flowblade version (Help->About):
2.8

2) MLT version (Help->Runtime Environment):
No such info

3) Distribution: 
Arch

4) If possible, try to provide step-by-step instructions on how to reproduce the issue. From developer point of view this is the easieast way to understand what is happening.:
When I run flowblade, it crashes with a Python error.
```
Player initialized with profile:  HD 1080p 30 fps
Traceback (most recent call last):
  File "/usr/bin/flowblade", line 93, in <module>
    app.main(modules_path)
  File "/usr/lib/python3.11/site-packages/Flowblade/app.py", line 307, in main
    create_gui()
  File "/usr/lib/python3.11/site-packages/Flowblade/app.py", line 487, in create_gui
    editor_window = editorwindow.EditorWindow()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/Flowblade/editorwindow.py", line 157, in __init__
    self._init_panels_and_frames()
  File "/usr/lib/python3.11/site-packages/Flowblade/editorwindow.py", line 656, in _init_panels_and_frames
    self.notebook.set_size_request(appconsts.NOTEBOOK_WIDTH, appconsts.TOP_ROW_HEIGHT)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'set_size_request'
```
[output.txt](https://github.com/jliljebl/flowblade/files/11852582/output.txt)
Sadly I don't know how to replicate this. Removing `~/.config/flowblade` fixes the issue.
Configuration files in `~/.config/flowblade`:
[config_files.zip](https://github.com/jliljebl/flowblade/files/11852588/config_files.zip)

**Comment by jliljebl** [comment]
Can you try the new Flatpak version 2.10.0.1? Installing instructions here: https://github.com/jliljebl/flowblade/blob/master/flowblade-trunk/docs/INSTALLING.md

**Comment by Wolfyxon** [comment]
Oh wait, there's a newer version? Weird that it's not in the Arch repos.
I installed it, inserted the config files from the repo version and still got the error.
```
Traceback (most recent call last):
  File "/app/bin/flowblade", line 93, in <module>
    app.main(modules_path)
  File "/app/share/flowblade/Flowblade/app.py", line 315, in main
    create_gui()
  File "/app/share/flowblade/Flowblade/app.py", line 491, in create_gui
    editor_window = editorwindow.EditorWindow()
  File "/app/share/flowblade/Flowblade/editorwindow.py", line 161, in __init__
    self._init_panels_and_frames()
  File "/app/share/flowblade/Flowblade/editorwindow.py", line 763, in _init_panels_and_frames
    self.notebook.set_tab_pos(Gtk.PositionType.BOTTOM)
AttributeError: 'NoneType' object has no attribute 'set_tab_pos'
GPU test results {'NVENC H.264 High Profile / .mp4': 0, 'NVENC HEVC Main10 Profile / .mp4': 0, 'VAAPI H.264 / .mp4': 0}
```

**Comment by jliljebl** [comment]
Confirmed,. Your config files crash the app at startup.

**Comment by jliljebl** [comment]
This is now fixed. Thanks for providing the config data, that was a great help. I'm in the process of pushing a quick fix release, this bug is bad enough to warrant one. Release 2.10.0.2 should be available in Flathub some time today.

**Comment by Wolfyxon** [comment]
Oh, thanks!
