### ISSUE TITLE
Opening flowblade causes python3.10 to quit unexpectedly

### ISSUE THREAD

**Issue by Solhex** [jliljebl/flowblade#1099]
Flowblade version: 2.10
MLT version: 7.17.0
Distribution: Fedora Linux 38 (Workstation Edition)
OS type: 64-bit
Desktop Environment: Gnome 44.2
Windowing system: Wayland
Kernel version: Linux 6.3.8-200.fc38.x86_64

Whenever I start-up flowblade or open a previous project I get the error message "python3.10 quit unexpectedly" from problem reporting, which spits out:

> reason: python3.10 killed by SIGSEGV
> cmdline: /usr/bin/python3 /app/share/flowblade/Flowblade/launch/flowbladegputestrender

Running the flatpak in cmdline with `-v`, when it starts the error occurs but nothing is printed out. However when opening a previous project it gets stuck loading the project trying to build a certain track, and the following is printed out to the cmdline:
```
window resized FAILED
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/app/share/flowblade/Flowblade/projectaction.py", line 130, in run
    project = persistance.load_project(self.filename)
  File "/app/share/flowblade/Flowblade/persistance.py", line 470, in load_project
    fill_sequence_mlt(seq, project.SAVEFILE_VERSION)
  File "/app/share/flowblade/Flowblade/persistance.py", line 530, in fill_sequence_mlt
    compositor = mlttransitions.create_compositor(py_compositor.type_id)
  File "/app/share/flowblade/Flowblade/mlttransitions.py", line 433, in create_compositor
    transition_info = mlt_compositor_transition_infos[compositor_type]
KeyError: '##auto_fade_in'
```

I didn't get this error few weeks before and it operated as expected, and from then I haven't really installed anything that could've messed with my system so I'm at a stump of what could've caused this.

**Comment by jliljebl** [comment]
These are two different problems

1) Gpu render issue:

  >  reason: python3.10 killed by SIGSEGV
  >  cmdline: /usr/bin/python3 /app/share/flowblade/Flowblade/launch/flowbladegputestrender

This is a bit baffling. Should happen everywhere if happens at all. The GPU render tests launch prosesses that are *supposed to crash* if some resource is not available, but that does not crash the application when running from developer version, or when running from Flatpak here.

I get e.g. 

> GPU test results {'NVENC H.264 High Profile / .mp4': 0, 'NVENC HEVC Main10 Profile / .mp4': 0, 'VAAPI H.264 / .mp4': -11}

printed on terminal as test results, and *-11 is indeed SIGSEGV*. But that is supposed to happen, I do:

```
        process = subprocess.Popen([sys.executable, respaths.LAUNCH_DIR + "flowbladegputestrender"], stdin=FLOG, stdout=FLOG, stderr=FLOG)
        try:
            out, err = process.communicate(timeout=5)
        except subprocess.TimeoutExpired:
            return -1
 
        return process.returncode
```

to run the tests and get the return values to find out which GPU render options are available.

But on your Fedora Linux 38, Gnome 44.2, Wayland that crashes the application, don't know why. Python Subpross API does not indicate that crashing Subprocess.process crashes parent process.

2) Load error:
```
window resized FAILED
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/app/share/flowblade/Flowblade/projectaction.py", line 130, in run
    project = persistance.load_project(self.filename)
  File "/app/share/flowblade/Flowblade/persistance.py", line 470, in load_project
    fill_sequence_mlt(seq, project.SAVEFILE_VERSION)
  File "/app/share/flowblade/Flowblade/persistance.py", line 530, in fill_sequence_mlt
    compositor = mlttransitions.create_compositor(py_compositor.type_id)
  File "/app/share/flowblade/Flowblade/mlttransitions.py", line 433, in create_compositor
    transition_info = mlt_compositor_transition_infos[compositor_type]
KeyError: '##auto_fade_in'
```

This one makes more sense and should be fixable.

**Comment by jliljebl** [comment]
BTW, is possible for you to test this bug:

> reason: python3.10 killed by SIGSEGV
> cmdline: /usr/bin/python3 /app/share/flowblade/Flowblade/launch/flowbladegputestrender

running Gnome on XOrg, so  we would know if this is Wayland related issue?

**Comment by Solhex** [comment]
Just tested it on Gnome XOrg and unfourtantely I got the exact same issue.

**Comment by Solhex** [comment]
The new update has just fixed the main issue for me, the load error, I'm now back to editing. Thanks!

**Comment by thennicke** [comment]
I know this is marked as fixed, but I still have the same SIGSEGV issue and get annoying notifications that Python has crashed every time I open Flowblade. See attached image from the problem reporting tool:
![Screenshot From 2024-12-31 10-55-50](https://github.com/user-attachments/assets/41de8489-3da2-452a-8307-61e45096467b)

If you want any information from me to help resolve this please let me know. I'm on Fedora 41 Wayland. Thanks.

**Comment by jliljebl** [comment]
I'll reopen and give this some further examination.

**Comment by takuvata** [comment]
Fedora 41 here, flatpak version, multiple 'python 3.11 crashed' notifications on every startup.

To be clear - this does not crash the application. Application seems to be working. Just getting this spam of crash reports on every start-up is really annoying. I sort of do understand the whole 'test the render methods' thing, however I don't think interpreter's segmentation faults should ever be considered 'normal and expected' even if it's just in some test subprocess.

Realistically, however, that segfault happens when mlt.consumer tries to start with params for NVENC on system that does not have cuda libraries (fails to load libcuda.so.1), so not sure if there's any elegant fix here from application side possible.

Ugly workaround I tested to be working on AMD-only machine and also Nvidia+Intel laptop:

```patch
diff --git a/flowblade-trunk/Flowblade/rendergputest.py b/flowblade-trunk/Flowblade/rendergputest.py
index 36e19828..39d97714 100644
--- a/flowblade-trunk/Flowblade/rendergputest.py
+++ b/flowblade-trunk/Flowblade/rendergputest.py
@@ -86,7 +86,9 @@ class GPUTestRunnerThread(threading.Thread):
         working_NVENC_encs = []
         for item in renderconsumer.NVENC_encs:
             name, enc_opt = item
-            returncode = self._test_encoder_option(name, enc_opt)
+            returncode = subprocess.call("ldconfig -p | grep -q libcuda", shell=True)
+            if returncode == 0:
+                returncode = self._test_encoder_option(name, enc_opt)
             test_results[name] = returncode
             if returncode == 0:
                 working_NVENC_encs.append((enc_opt.name, enc_opt))
```

On AMD-only machine I get:
```
Create SDL2 consumer...
GPU test results {'NVENC H.264 High Profile / .mp4': 1, 'NVENC HEVC / .mp4': 1, 'NVENC HEVC HDR / .mp4': 1, 'VAAPI H.264 / .mp4': 0}
```

On Nvidia+Intel laptop:
```
Create SDL2 consumer...
GPU test results {'NVENC H.264 High Profile / .mp4': 0, 'NVENC HEVC / .mp4': 0, 'NVENC HEVC HDR / .mp4': 0, 'VAAPI H.264 / .mp4': 0}
```

No more 'python crashed' and tests, I assume - make the right conclusions.
