### ISSUE TITLE
2.10 Slow/Fast Motion Render Hands at "Render Starting..."

### ISSUE THREAD

**Issue by PhiloEpisteme** [jliljebl/flowblade#1105]
Flowblade Version: 2.10
MLT Version: 7.17.0
OS: Ubuntu 22.04
Install Method: Flatpak

Similar to Issues #913 I am having an issue with the  slow motion tool. I can reproduce the bug by selecting a clip -> right click -> edit -> export to tool -> slow / fast motion -> set a <100% speed -> render. When I follow these steps, the list of render jobs shows this slow motion job as always in "Render Starting ...".

I have tried the solution given in the issue linked above by making sure that I do `chmod a+x` on the `motionheadless.py` file without any luck.

If I invoke flowblade via flatpak and follow the steps above I get the following error logs

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/app/share/flowblade/Flowblade/tools/motionheadless.py", line 91, in run
    motion_producer = mlt.Producer(profile, None, str("timewarp:" + str(self.speed) + ":" + str(self.source_path)))
  File "/app/lib/python3.10/site-packages/mlt7.py", line 977, in __init__
    this = _mlt7.new_Producer(*args)
ValueError: invalid null reference in method 'new_Producer', argument 1 of type 'Mlt::Profile &'
```

**Comment by jliljebl** [comment]
Not reproducing on developer version or on the Flatpak 2.10.04 installed on my system.  Before next release I'll install Ubuntu 22.04 on Virtual Box (I have  Ubuntu 23.04), install Flatpak and see if I get the error reproduced.

**Comment by JeffreyHarpen** [comment]
I have exactly the same issue. I haven't tried any fixes because I don't want to break anything.

Flowblade Version: 2.16.3
MLT Version: I have no idea
OS: SteamOS (on Steam Deck)
Install Method: Discovery (built-in store app)

**Comment by jliljebl** [comment]
I'll re-try to reproduce before next release.
