### ISSUE TITLE
Crashes while viewing clip

### ISSUE THREAD

**Issue by fjsal07** [jliljebl/flowblade#1115]
Please include the following information.
1) Flowblade version (Help->About): 2.10.0.4
2) MLT version (Help->Runtime Environment): 7.17.0
3) Your distribution (Ubuntu, Debian, Mint etc.): Linux Mint 21.2 Victoria
4) If possible, try to provide step-by-step instructions on how to reproduce the issue. From developer point of view this is the easieast way to understand what is happening.: 

Crash playing video after adding title. Did not crash at the title though:
*** BUG ***
In pixman_region_append_non_o: The expression y1 < y2 was false
Set a breakpoint on '_pixman_log_error' to debug

[image2 @ 0x7f4378bd62c0] The specified filename '/home/fjs/.var/app/io.github.jliljebl.Flowblade/cache/flowblade/thumbnails/8060e0572de8c481285740a8cd93706a.png' does not contain an image sequence pattern or a pattern is invalid.
[image2 @ 0x7f4378bd62c0] Use a pattern such as %03d for an image sequence or use the -update option (with -frames:v 1 if needed) to write a single image.

Another crash viewing clips on timeline, just after creating a title:
[image2 @ 0x7f4378bd62c0] The specified filename '/home/fjs/.var/app/io.github.jliljebl.Flowblade/cache/flowblade/thumbnails/8060e0572de8c481285740a8cd93706a.png' does not contain an image sequence pattern or a pattern is invalid.
[image2 @ 0x7f4378bd62c0] Use a pattern such as %03d for an image sequence or use the -update option (with -frames:v 1 if needed) to write a single image.

Lots of this in command line output even if no immediate crash:
[m[mp3float @ 0x7f7329f7e300] Could not update timestamps for skipped samples.

Viewing clip that was sped up 25% in viewer:
[swscaler @ 0x7fbbe4000900] deprecated pixel format used, make sure you did set range correctly
[swscaler @ 0x7fbbe8000900] deprecated pixel format used, make sure you did set range correctly
[swscaler @ 0x7fbbf0000900] deprecated pixel format used, make sure you did set range correctly
[mp4 @ 0x7fbc28000f40] Timestamps are unset in a packet for stream 1. This is deprecated and will stop working in the future. Fix your code to set the timestamps properly
[mp4 @ 0x7fbc28000f40] Encoder did not produce proper pts, making some up.
FileRenderPlayer stopped, producer frame: 1185
[image2 @ 0x7fa0f3f99d80] The specified filename '/home/fjs/.var/app/io.github.jliljebl.Flowblade/cache/flowblade/thumbnails/ba3f122dbbab5b639ce2bb1e61d17eca.png' does not contain an image sequence pattern or a pattern is invalid.
[image2 @ 0x7fa0f3f99d80] Use a pattern such as %03d for an image sequence or use the -update option (with -frames:v 1 if needed) to write a single image.
Saving project...
[mp3float @ 0x7fa1981ca300] Could not update timestamps for skipped samples.

Thank you for creating this great application! I toy with Python programming and I can't imagine the complexity of code this must take.

**Comment by fjsal07** [comment]
Updated to add formatting that I originally forgot to do, and make post clearer. Anyone having similar problems?

**Comment by wolfgangr** [comment]
I also have trouble with the "swscaler deprecated pixel format" issue, however, no crashes yet.
however, I just rendered a tiny 60 frame snippet via GPU to a proxy file, I count this message some fourhundred thousand [sic!] times.

It seems to relate to an long known ffmpeg issue, in sluggy dealing with mpeg pixel format.
see eg here 
https://trac.ffmpeg.org/ticket/6088
or here
https://git.videolan.org/?p=ffmpeg.git;a=commitdiff;h=b2d1a258162a619187bbb0a72f7e8eb94f91cfa4

I'll keep you informed

**Comment by jliljebl** [comment]
```
after some testing I think I can tell, regarding flowblade, it seems to be the other way round:
fb expects yuv420p , and if it gets yuvj420p, it performs conversion, resulting in deprecated pixel format warnings.

I can check files with ffprobe MYFILE.name which colorformat is used.

I can convert with

ffmpeg  -hwaccel cuda -i $INFILE \
        -c:a aac \
        -c:v h264_nvenc -rc vbr -cq 28 -pix_fmt yuv420p  ${BASENAME}_h264_cq28_yuv420p.mp4

without GPU acceleration this might look like
 ffmpeg -i DSCF0013.AVI  -c:v libx264 -pix_fmt yuv420p  -c:a aac output.mp4

Loading such converted videos into flowblade does not show any visual difference and renders without the deprecated pixel format warnings.

Mabe it is a helpful workaraound in your case.
```

@wolfgangr  thanks, I'll do some comparing with other MLT based apps to see if I'm indeed doing something wrong here or could MLt be patched to get improvement here.

**Comment by jliljebl** [comment]
```
[image2 @ 0x7f4378bd62c0] The specified filename '/home/fjs/.var/app/io.github.jliljebl.Flowblade/cache/flowblade/thumbnails/8060e0572de8c481285740a8cd93706a.png' does not contain an image sequence pattern or a pattern is invalid.
[image2 @ 0x7f4378bd62c0] Use a pattern such as %03d for an image sequence or use the -update option (with -frames:v 1 if needed) to write a single image.
```
Pushed a patch to fix this complaint when creating thumbnails.

**Comment by jliljebl** [comment]
On latest flatpak or my dev I'm not getting:

```
Gtk-Message: 12:54:20.512: Failed to load module "xapp-gtk3-module"
```
which is not surprising,Flowblade does not use any xapp functionality, as listed here: https://projects.linuxmint.com/xapp/reference/index.html. I'm pretty sure issue is with Linux Mint 21.2 as libxapp readme says: *"This project gathers the components which are common to multiple GTK desktop environments"*.  That seems something that Mint could be using.

**Comment by fjsal07** [comment]
Thanks guys for the good information and quick response. I can ignore the bogus warnings, but the crashes are quite inconvenient.  I had another one yesterday, but I don't have any CL output since I started Flowblade from the Mint menu. 
Should I report the Gtk error to Mint?

**Comment by fjsal07** [comment]
I just had 2 crashes in short order. One was the common issue:
`swscaler @ 0x7f64f0000900] deprecated pixel format used, make sure you did set range correctly`

But the second one was partially new:
```
[swscaler @ 0x7f64f0000900] deprecated pixel format used, make sure you did set range correctly
[swscaler @ 0x7f64dc000900] deprecated pixel format used, make sure you did set range correctly
[swscaler @ 0x7f64dc000900] deprecated pixel format used, make sure you did set range correctly
[swscaler @ 0x7f64f0000900] deprecated pixel format used, make sure you did set range correctly
*** BUG ***
In pixman_region_append_non_o: The expression y1 < y2 was false
Set a breakpoint on '_pixman_log_error' to debug

*** BUG ***
In pixman_region_append_non_o: The expression y1 < y2 was false
Set a breakpoint on '_pixman_log_error' to debug

malloc(): unaligned fastbin chunk detected
```
I know malloc() is a C function, and Python is written in C, but I have never seen a C error show up in Python crashes before. Perhaps a clue?

**Comment by fjsal07** [comment]
I tried the ffmpeg code you gave to convert a short clip. I closed the existing projecy in Flowblade, the imported the converted clip. Inserted it 3 times on the V1 timeline and played it a couple of times. Spiit one of the clips, then deleted the 1st half. during playback I got another crash, different again:

```
Saving project...
Adding full track compositors
restacking compositors!
Adding full track compositors DONE
Player initialized with profile:  HD 1080p 30 fps
Create SDL1 consumer...
restacking compositors!
Autosave started...
Saving project...
[image2 @ 0x7faa8425aa80] The specified filename '/home/fjs/.var/app/io.github.jliljebl.Flowblade/cache/flowblade/thumbnails/325341d8e30769279cb2f78383465392.png' does not contain an image sequence pattern or a pattern is invalid.
[image2 @ 0x7faa8425aa80] Use a pattern such as %03d for an image sequence or use the -update option (with -frames:v 1 if needed) to write a single image.
Saving project...
restacking compositors!
Player initialized with profile:  HD 1080p 23.98 fps
Create SDL1 consumer...
restacking compositors!
Autosave started...
Saving project...
Updating media lengths done.
Project file moved since last save, save with updated last_save_path data.
Saving project...
Saving project...
Saving project...
*** BUG ***
In pixman_region_append_non_o: 
```


The converted clip played fine in both VLC and Flowblade. Maybe I did something wrong in the conversion.
```

**Comment by jliljebl** [comment]
Can you try the Flatpak version: https://flathub.org/apps/io.github.jliljebl.Flowblade

Linux Mint 21.2 Victoria should support Flatpaks and you can just press install on the webpage.

**Comment by fjsal07** [comment]
I am using a Flatpack install, to get the latest version. I didn't use the one in the Mint repositories, because it was v2.8. But maybe something wrong with Mint's Flatpack version? I will try the one you suggested.

**Comment by fjsal07** [comment]
Installed the Flatpack suggested above and all went well for a while, then another crash. It was preceded by many, many lines of the same 
`deprecated pixel format used,` error, but those had been there even when things were working fine. Also, still got the GTK warning on startup.

**Comment by jliljebl** [comment]
Ok. 

Can you make one of the clips that cause the crash in your system downloadable somehow so I can try to reproduce the issue on my system?

**Comment by fjsal07** [comment]
Yes, of course, here is a link to the last clip that I experienced a  crash on:
[https://photos.app.goo.gl/5UcfkfLGssLGgGfv8]

Just to be clear, the crashes seem random and not limited to this clip.
And if it makes an difference, all clips I am using were taken with a Pixel 6a phone.

Here is some information from Google Photos that may or may not be relevant:
`Video ID / sCPN
AF1QipO9PIwtsCZR8fzOC04AFGLdvWff2SO8UPaK1hAo / WHX1 9WAE 2W8F
Viewport / Frames
1552x873 / 0 dropped of 403
Current / Optimal Res
1920x1080 / 1920x1080
Volume / Normalized
100% / 100%
Codecs
avc1.64001F, mp4a.40.2 (15)
Buffer Health
14.67 s
Mystery Text
s:4 t:1.12 b:0.000-15.783 P pl_i:1
Date
Thu Oct 12 2023 10:18:37 GMT-0600 (Mountain Daylight Time)
0:01 / 0:15
`
This is debug info from viewer in Google Photos:
`{
  "ns": "pw",
  "el": "embedded",
  "cpn": "5HoU8U4XEPJK_8wd",
  "ver": 2,
  "cmt": "2.545",
  "fmt": "15",
  "fs": "0",
  "rt": "131.228",
  "euri": "https://youtube.googleapis.com/",
  "lact": 1,
  "cl": "571789013",
  "mos": 0,
  "state": "4",
  "volume": 100,
  "cbr": "Firefox",
  "cbrver": "118.0",
  "c": "WEB_EMBEDDED_PLAYER",
  "cver": "1.20231008.00.00",
  "cplayer": "UNIPLAYER",
  "cos": "X11",
  "cplatform": "DESKTOP",
  "hl": "en_US",
  "cr": "US",
  "len": "15.803",
  "fexp": "v1,23858057,125239,21348,2602,73492,54572,73455,176962,53634,84737,17459,17771,1088,6271,249,2951,18465,26417829,3518,536,1253,677,6724,8049,1333,2040,564,4369,3155",
  "muted": "0",
  "docid": "AF1QipO9PIwtsCZR8fzOC04AFGLdvWff2SO8UPaK1hAo",
  "vct": "2.545",
  "vd": "15.803",
  "vpl": "0.000-2.545,4.218-15.803",
  "vbu": "0.000-15.783",
  "vpa": "1",
  "vsk": "0",
  "ven": "0",
  "vpr": "1",
  "vrs": "4",
  "vns": "1",
  "vec": "null",
  "vemsg": "",
  "vvol": "1",
  "vdom": "1",
  "vsrc": "1",
  "vw": "1552",
  "vh": "873",
  "relative_loudness": "NaN",
  "optimal_format": "720p",
  "user_qual": 0,
  "release_version": "youtube.player.web_20231008_00_RC00",
  "debug_videoId": "AF1QipO9PIwtsCZR8fzOC04AFGLdvWff2SO8UPaK1hAo",
  "0sz": "false",
  "op": "",
  "yof": "false",
  "dis": "",
  "gpu": "GeForce_GTX_480/PCIe/SSE2",
  "debug_playbackQuality": "hd720",
  "debug_date": "Thu Oct 12 2023 10:19:10 GMT-0600 (Mountain Daylight Time)",
  "timestamp": 1697127550857
}`

**Comment by fjsal07** [comment]
I don't mean to overwhelm you with data but I had another crash and looked at my logs. I thought it might be useful.

Crash while editing a video with a dozen or so clips. Split a short clip (not the one I linked to in previous message), then muted audio in 2nd part. Crashed while playing:
/var/log/kern.log
```
Oct 12 14:06:58 i620 kernel: [17416.056243] flowblade[40816]: segfault at 21b00000640 ip 00007f5115365bd9 sp 00007fffbc49a600 error 4 in libglib-2.0.so.0.7600.5[7f5115327000+a0000]
Oct 12 14:06:58 i620 kernel: [17416.056270] Code: 44 8b 8d 78 ff ff ff 83 6b 58 01 45 85 c9 75 26 49 8b 4e 58 48 8b 41 18 48 85 c0 75 0d eb 5a 66 90 48 8b 40 08 48 85 c0 74 4f <48> 8b 10 66 83 7a 06 00 74 ed eb 04 49 8b 4e 58 41 83 4e 2c 10 48
```
/var/log/syslog
```
Oct 12 14:06:58 i620 kernel: [17416.056243] flowblade[40816]: segfault at 21b00000640 ip 00007f5115365bd9 sp 00007fffbc49a600 error 4 in libglib-
2.0.so.0.7600.5[7f5115327000+a0000]
Oct 12 14:06:58 i620 kernel: [17416.056270] Code: 44 8b 8d 78 ff ff ff 83 6b 58 01 45 85 c9 75 26 49 8b 4e 58 48 8b 41 18 48 85 c0 75 0d eb 5a 66
 90 48 8b 40 08 48 85 c0 74 4f <48> 8b 10 66 83 7a 06 00 74 ed eb 04 49 8b 4e 58 41 83 4e 2c 10 48
Oct 12 14:06:15 i620 rtkit-daemon[1092]: message repeated 3 times: [ Supervising 7 threads of 5 processes of 1 users.]
Oct 12 14:06:58 i620 systemd[1]: Started Process Core Dump (PID 41159/UID 0).
Oct 12 14:07:08 i620 systemd-coredump[41160]: Process 40816 (flowblade) of user 1000 dumped core.#012#012Found module /usr/bin/python3.10 with bu
ild-id: 3ec5a1f037dc1eb594c3a315723add3173fb7355#012Found module /app/lib/frei0r-1/squareblur.so with build-id: bee213f39c5d31a55d1d18a48845b6300
54b5ad3#012Found module /usr/lib/x86_64-linux-gnu/libibus-1.0.so.5.0.525 with build-id: e7e31557d70d29bca41e9c9e711114615bd66dc3#012Found module 
/usr/lib/x86_64-linux-gnu/gtk-3.0/3.0.0/immodules/im-ibus.so with build-id: a17c0ada8b0d757d9038266a7e7f0597dfec7233#012Found module /app/lib/fre
i0r-1/rgbparade.so with build-id: 6a2cb58ddba0f44a84e8359d9e02f1200b17b7d3#012Found module /app/lib/libgavl.so.1.0.0 with build-id: a392dcce5a9dd
d12427a7ef1a484d1c057236820#012Found module /app/lib/frei0r-1/vectorscope.so with build-id: fd6cb73a8741b2e4ecbd0b5a7c1918c4a1247e64#012Found mod
ule /usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-svg.so with build-id: f95c024a9b931461d1a9de53a1a04ddf200e70ec#012Fou
nd module /usr/lib/x86_64-linux-gnu/gio/modules/libgioremote-volume-monitor.so with build-id: b2191aacb412031679c6f3cc4ca81928f876ddd5#012Found m
odule /app/lib/frei0r-1/cairoblend.so with build-id: 5eac289a95bf2208cd35cc55b15af376e34092d5#012Found module /app/lib/mlt-7/libmltoldfilm.so wit
h build-id: a8ab2d497764b02cb9614d60bcc322a7d0eaacb5#012Found module /app/lib/mlt-7/libmltdecklink.so with build-id: b259c80301ae8f475546f596252e
8d0dce8e25ba#012Found module /app/lib/mlt-7/libmltrtaudio.so with build-id: 73a9326e37d57656e9794754ad5e9d0bcc122eda#012Found module /app/lib/mlt
-7/libmltnormalize.so with build-id: 87ec008f5c48c3d5ebf5288fdb18336a40e61420#012Found module /app/lib/mlt-7/libmltplusgpl.so with build-id: 3fd2
7c14105ff31b6df56fcf2d1676324520e2bb#012Found module /app/lib/mlt-7/libmltsdl2.so with build-id: b7f84fd6c363b7c7abeb7a87c8ecd3512c4770ba#012Foun
d module /app/lib/mlt-7/libmltcore.so with build-id: 972cbbd4d95121f0594988afed60d10fcd240ea2#012Found module /usr/lib/x86_64-linux-gnu/libexif.s
o.12.3.4 with build-id: d7463248024d939ceec5d55a7d23de2021ebd324#012Found module /app/lib/mlt-7/libmltvorbis.so with build-id: 315a4bd10302488086
05cdc2c9bc172c074cd2ec#012Found module /app/lib/mlt-7/libmltgdk.so with build-id: 5cb370d8fb1304f145fc00735441fb64dae194e8#012Found module /usr/l
ib/x86_64-linux-gnu/spa-0.2/support/libspa-support.so with build-id: e61bdd06cd85c12189e016b6c61b82b7f0b156a0#012Found module /usr/lib/x86_64-lin
ux-gnu/libpipewire-0.3.so.0.369.0 with build-id: 4390bde0af59499bab9dfc91cb3fd5d62f474f58#012Found module /usr/lib/x86_64-linux-gnu/libjack.so.0.
369.0 with build-id: 74ae91a8a0a9900593d59def5ec74cc2f2a2f436#012Found module /app/lib/mlt-7/libmltjackrack.so with build-id: 7507e948b45fc6dd929
8ec4757a4cc8e26949c50#012Found module /usr/lib/x86_64-linux-gnu/libsamplerate.so.0.2.2 with build-id: e7f07be69f4d140fb0055891ad652c11744f9107#01
2Found module /usr/lib/x86_64-linux-gnu/spa-0.2/support/libspa-journal.so with build-id: 1d8d82969ed9832b2c35bec5b1d0dc7263672755#012Found module
 /usr/lib/x86_64-linux-gnu/libgomp.so.1.0.0 with build-id: 2a112948b1850d1f81a986b5d7fbb98a58c8ca75#012Found module /usr/lib/x86_64-linux-gnu/lib
wavpack.so.1.2.5 with build-id: f33b14c156cc7064539afe8597de765123910e36#012Found module /usr/lib/x86_64-linux-gnu/libvorbisfile.so.3.3.8 with bu
ild-id: 0c2d1c44c324454baaffd10659848c0ff2f3e7bc#012
```

**Comment by jliljebl** [comment]
Thanks, looked at the clip. Didn't crash on first try. I'll do longer test later and try to play with it longer, add filters, use in on multiple tracks, split audio etc. to see if crashes start to occur.

**Comment by fjsal07** [comment]
Thank you. I tried the open source video driver instead of the nVidia one.
Still had a crash. The nVidea driver manager has lots of settings, but I
don't understand most of them. I don't know if any of those would help
anyway.

**Comment by fjsal07** [comment]
A possible clue; I got a GoPro and have been using Flowblade to edit it's videos. No actual crashes yet but I did get 2 lockups and lots of error messages:
While trying to view color clip in Clip Monitor so I could insert it:
```
Traceback (most recent call last):
  File "/app/share/flowblade/Flowblade/projectaction.py", line 954, in media_panel_double_click
    updater.set_and_display_monitor_media_file(media_file)
  File "/app/share/flowblade/Flowblade/updater.py", line 546, in set_and_display_monitor_media_file
    display_clip_in_monitor()
  File "/app/share/flowblade/Flowblade/updater.py", line 356, in display_clip_in_monitor
    if MONITOR_MEDIA_FILE().container_data != None:
AttributeError: 'BinColorClip' object has no attribute 'container_data'
Traceback (most recent call last):
  File "/app/share/flowblade/Flowblade/projectaction.py", line 2121, in media_file_menu_item_selected
    updater.set_and_display_monitor_media_file(media_file)
  File "/app/share/flowblade/Flowblade/updater.py", line 546, in set_and_display_monitor_media_file
    display_clip_in_monitor()
  File "/app/share/flowblade/Flowblade/updater.py", line 356, in display_clip_in_monitor
    if MONITOR_MEDIA_FILE().container_data != None:
AttributeError: 'BinColorClip' object has no attribute 'container_data'
Traceback (most recent call last):
  File "/app/share/flowblade/Flowblade/projectaction.py", line 954, in media_panel_double_click
    updater.set_and_display_monitor_media_file(media_file)
  File "/app/share/flowblade/Flowblade/updater.py", line 546, in set_and_display_monitor_media_file
    display_clip_in_monitor()
  File "/app/share/flowblade/Flowblade/updater.py", line 356, in display_clip_in_monitor
    if MONITOR_MEDIA_FILE().container_data != None:
AttributeError: 'BinColorClip' object has no attribute 'container_data'
Traceback (most recent call last):
  File "/app/share/flowblade/Flowblade/projectaction.py", line 2121, in media_file_menu_item_selected
    updater.set_and_display_monitor_media_file(media_file)
  File "/app/share/flowblade/Flowblade/updater.py", line 546, in set_and_display_monitor_media_file
    display_clip_in_monitor()
  File "/app/share/flowblade/Flowblade/updater.py", line 356, in display_clip_in_monitor
    if MONITOR_MEDIA_FILE().container_data != None:
AttributeError: 'BinColorClip' object has no attribute 'container_data'
```

Flowblade was then unresponsive for 3-5 minutes.

Then, right clicking on the color clip and selecting Open in Clip Monitor, I get this error:
```
Traceback (most recent call last):
  File "/app/share/flowblade/Flowblade/projectaction.py", line 2121, in media_file_menu_item_selected
    updater.set_and_display_monitor_media_file(media_file)
  File "/app/share/flowblade/Flowblade/updater.py", line 546, in set_and_display_monitor_media_file
    display_clip_in_monitor()
  File "/app/share/flowblade/Flowblade/updater.py", line 356, in display_clip_in_monitor
    if MONITOR_MEDIA_FILE().container_data != None:
AttributeError: 'BinColorClip' object has no attribute 'container_data'
```

Flowblade was again unresponsive, but for a shorter time. It never actually crashed in either instance. Note also that I am using GoPro clips
at 1080p 30fps and have not had a crash in a couple of days. I still need to edit video from the phone though.

**Comment by jliljebl** [comment]
Thanks, this a bug I can reproduce and fix, probably not related to the other Issue though.

**Comment by jliljebl** [comment]
```
Traceback (most recent call last):
  File "/app/share/flowblade/Flowblade/projectaction.py", line 2121, in media_file_menu_item_selected
    updater.set_and_display_monitor_media_file(media_file)
  File "/app/share/flowblade/Flowblade/updater.py", line 546, in set_and_display_monitor_media_file
    display_clip_in_monitor()
  File "/app/share/flowblade/Flowblade/updater.py", line 356, in display_clip_in_monitor
    if MONITOR_MEDIA_FILE().container_data != None:
AttributeError: 'BinColorClip' object has no attribute 'container_data'
```
This is now fixed in repo.

I did a longer edit with file the you send and got no crashes. The only thing that that seemed peculiar about the file was that it had speed marked as 29.86 fps, which is very non-standard frames per second value.

I did a do a web search on the error message and in one seemed to be involved with some GTK locking issues, but that would crash always, not with just some files. 

I'll keep this open and see if we new get some ideas on what this is about.

**Comment by fjsal07** [comment]
Thank you. Yes I noticed the frame rate, but didn't think anything of it. I
was always clicking yes to conversion on the dialog that pops up saying  "A
video file was loaded that does not match project profile." . I tried NOT
converting with the GoPro footage that I shot at 1080p 30fps and it
crashed. Same footage, but letting Flowblade convert has not caused any
issues so far. Curiously, it shows 29.97fps. I thought this was close
enough, so I did not convert it the first time, and got a crash.
What distro do you develop and test Flowblade on?
