### ISSUE TITLE
Startup fails on create_compositor

### ISSUE THREAD

**Issue by ExecutorElassus** [jliljebl/flowblade#1116]
flowblade-2.11-dev
MLT 7.18.0
gentoo linux, cloned from git

startup fails with the following error:

```
$ apulse ./flowblade 
FLOWBLADE MOVIE EDITOR 2.11-dev
-------------------------------
Launch script dir: /path/to/clone/flowblade/flowblade/flowblade-trunk
Running from filesystem...
MLT found, version: 7.18.0
numpy version: 1.26.0
Application version: 2.10.0
OS: Gentoo Linux
Python 3.12.0rc3 (main, Sep 29 2023, 13:15:43) [GCC 13.2.1 20230826]
GTK+ version: 3.24.38
XDG Config ~/.config/flowblade
XDG Data ~/.local/share/flowblade
XDG Cache ~/.cache/flowblade
Locale: en_US
Found translations at /path/to/clone/flowblade/flowblade/flowblade-trunk/Flowblade/locale/, using those.
Use OS locale language.
Valid shortcut files found: ['flowblade.xml', 'premiere.xml']
Keyboard shortcuts file: flowblade.xml
Using Full Screen size for layout: 3840 x 2400
Small height: False
Small width: False
Detecting environment...
---

[SNIP]
MLT transition frei0r.alphain not found.
MLT transition frei0r.alphaout not found.
Gamma dropped for Lift Gain Gamma
Adding full track compositors
Traceback (most recent call last):
  File "/path/to/clone/flowblade/flowblade/flowblade-trunk/Flowblade/app.py", line 306, in on_activate
    editorstate.project = projectdata.get_default_project()
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/clone/flowblade/flowblade/flowblade-trunk/Flowblade/projectdata.py", line 610, in get_default_project
    project = Project(profile)
              ^^^^^^^^^^^^^^^^
  File "/path/to/clone/flowblade/flowblade/flowblade-trunk/Flowblade/projectdata.py", line 106, in __init__
    self.add_unnamed_sequence()
  File "/path/to/clone/flowblade/flowblade/flowblade-trunk/Flowblade/projectdata.py", line 277, in add_unnamed_sequence
    self.add_named_sequence(name)
  File "/path/to/clone/flowblade/flowblade/flowblade-trunk/Flowblade/projectdata.py", line 281, in add_named_sequence
    seq.create_default_tracks()
  File "/path/to/clone/flowblade/flowblade/flowblade-trunk/Flowblade/sequence.py", line 211, in create_default_tracks
    self.add_full_track_compositors()
  File "/path/to/clone/flowblade/flowblade/flowblade-trunk/Flowblade/sequence.py", line 715, in add_full_track_compositors
    compositor = self.create_compositor("##blend")
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/clone/flowblade/flowblade/flowblade-trunk/Flowblade/sequence.py", line 619, in create_compositor
    compositor.create_mlt_objects(self.profile)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'create_mlt_objects'
GPU test results {'VAAPI H.264 / .mp4': 0}
```

**Comment by ExecutorElassus** [comment]
Update: please disregard the previous error messages; I was missing dependencies for mlt, frei0r, and opencv support. Now I'm getting an entirely new error, something related to SDL:

```
MLT service ladspa.1201 not found.
Loading transitions...
RGB Adjustment dropped for Color Adjustment
Hue dropped for Color Adjustment
Gamma dropped for Lift Gain Gamma
Adding full track compositors
restacking compositors!
Adding full track compositors DONE
active_vault 0
[]
G'MIC found
Player initialized with profile:  HD 1080p 30 fps
Create SDL1 consumer...
Fatal Python error: Segmentation fault

Thread 0x00007fdfcedb56c0 (most recent call first):
  File "/usr/lib/python3.12/subprocess.py", line 2040 in _wait
  File "/usr/lib/python3.12/subprocess.py", line 1264 in wait
  File "/usr/lib/python3.12/subprocess.py", line 2134 in _communicate
  File "/usr/lib/python3.12/subprocess.py", line 1209 in communicate
  File "/path/to/clone/flowblade/flowblade/flowblade-trunk/Flowblade/rendergputest.py", line 136 in _test_encoder_option
  File "/path/to/clone/flowblade/flowblade/flowblade-trunk/Flowblade/rendergputest.py", line 101 in run
  File "/usr/lib/python3.12/threading.py", line 1052 in _bootstrap_inner
  File "/usr/lib/python3.12/threading.py", line 1009 in _bootstrap

Current thread 0x00007fdfeb401740 (most recent call first):
  File "/usr/lib/python3.12/site-packages/mlt7.py", line 1088 in connect
  File "/path/to/clone/flowblade/flowblade/flowblade-trunk/Flowblade/mltplayer.py", line 169 in connect_and_start
  File "/path/to/clone/flowblade/flowblade/flowblade-trunk/Flowblade/app.py", line 549 in launch_player
  File "/path/to/clone/flowblade/flowblade/flowblade-trunk/Flowblade/app.py", line 342 in on_activate
  File "/usr/lib/python3.12/site-packages/gi/overrides/Gio.py", line 42 in run
  File "/path/to/clone/flowblade/flowblade/flowblade-trunk/Flowblade/app.py", line 201 in main
  File "/path/to/clone/flowblade/flowblade/flowblade-trunk/flowblade", line 93 in <module>

Extension modules: _mlt7, gi._gi, cairo._cairo, gi._gi_cairo, numpy.core._multiarray_umath, numpy.core._multiarray_tests, numpy.linalg._umath_linalg, numpy.fft._pocketfft_internal, numpy.random._common, numpy.random.bit_generator, numpy.random._bounded_integers, numpy.random._mt19937, numpy.random.mtrand, numpy.random._philox, numpy.random._pcg64, numpy.random._sfc64, numpy.random._generator, PIL._imaging, _dbus_bindings, _dbus_glib_bindings, PIL._imagingft (total: 21)
Segmentation fault
```
So it's still something wrong with MLT; am I missing some other dependency?

**Comment by ExecutorElassus** [comment]
update: MLT is pointing to SDL1, which on gentoo works through a compatibility layer. I'm doing some digging on the mlt github page, but is there some other way to work around MLT specifically calling SDL1?

See this issue: https://github.com/mltframework/mlt/issues/508

**Comment by ExecutorElassus** [comment]
update: I now see this is specifically a gentoo issue with MLT and SDL: https://github.com/jliljebl/flowblade/issues/649. I'll 
close this issue, then, since it's redundant. Sorry for the trouble!

**Comment by marillat** [comment]
This bug is still in 2.14.0.1
Debian unstable amd64 mlt 7.22
```
Loading filters...
MLT service frei0r.cairogradient not found.
MLT service frei0r.cairoimagegrid not found.
Loading transitions...
MLT transition frei0r.cairoaffineblend not found.
MLT transition frei0r.cairoblend not found.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/Flowblade/app.py", line 311, in on_activate
    editorstate.project = projectdata.get_default_project()
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/Flowblade/projectdata.py", line 647, in get_default_project
    project = Project(profile)
              ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/Flowblade/projectdata.py", line 108, in __init__
    self.add_unnamed_sequence()
  File "/usr/lib/python3/dist-packages/Flowblade/projectdata.py", line 299, in add_unnamed_sequence
    self.add_named_sequence(name)
  File "/usr/lib/python3/dist-packages/Flowblade/projectdata.py", line 312, in add_named_sequence
    seq.create_default_tracks()
  File "/usr/lib/python3/dist-packages/Flowblade/sequence.py", line 211, in create_default_tracks
    self.add_full_track_compositors()
  File "/usr/lib/python3/dist-packages/Flowblade/sequence.py", line 715, in add_full_track_compositors
    compositor = self.create_compositor("##blend")
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/Flowblade/sequence.py", line 624, in create_compositor
    compositor.create_mlt_objects(self.profile)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'create_mlt_objects'
GPU test results {'NVENC H.264 High Profile / .mp4': 0, 'NVENC HEVC / .mp4': 0, 'NVENC HEVC HDR / .mp4': 0, 'VAAPI H.264 / .mp4': -11}
```

**Comment by jliljebl** [comment]
Re-opening, will investigate.

**Comment by marillat** [comment]
This issue isn't related to a special mlt version.

I see the same with mlt 7.18

**Comment by jliljebl** [comment]
```
MLT transition frei0r.cairoaffineblend not found.
MLT transition frei0r.cairoblend not found.
```

The default project created on startup needs the *frei0r.cairoblend* compositor to be available. There are several reasons why that is not the case here.

1) Frei0r is not installed.
2) Cairo is not installed
3) Frei0r is installed, but was compiled in a way that Cairo plugins were not made part of the release.
4) MLT was compiled and installed without the Frei0r module.

I'll leave this open for now so that we might get some info on the particular cause here, but will close this later as this is not something that can be fixed with updates to Flowblade code.

**Comment by marillat** [comment]
> ```
>     3. Frei0r is installed, but was compiled in a way that Cairo plugins were not made part of the release.
```
The problem is here. Never noticed this issue before. You can close this "issue".

**Comment by jliljebl** [comment]
Thanks for the info, closing.
