### ISSUE TITLE
rendering text generators hangs on dev version

### ISSUE THREAD

**Issue by ExecutorElassus** [jliljebl/flowblade#1119]
1) Flowblade version (Help->About): 2.10 (github clone of dev version)
2) MLT version (Help->Runtime Environment): 7.18.0
3) Your distribution (Ubuntu, Debian, Mint etc.): gentoo

I'm pretty certain this is a missing/misconfigured dependency, since I do not have this error on the flatpak version. In the dev version, when I create a generator for a multiline text animation, putting it onto the timeline creates a render job that crashes with the following error in the console:

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.12/threading.py", line 1052, in _bootstrap_inner
    self.run()
  File "/path/to/flowblade/flowblade/flowblade-trunk/Flowblade/tools/fluxityheadless.py", line 168, in run
    _frame_range_update_thread.start()
  File "/usr/lib/python3.12/threading.py", line 971, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't create new thread at interpreter shutdown
```
The Jobs tab continually shows the job as "starting", and never completes. I can't quit flowblade or cancel the job, so I have to force-close it.

**Comment by ExecutorElassus** [comment]
So, this turns out to be a gentoo problem with MLT: MLT was always installing to the latest python version on the system, even when configured otherwise. The cloned git version doesn't check for that, and only looks for mlt7 in the subdirectory matching its own python version. This was causing problems. 
I've patched MLT and now it works correctly. So I'll close this issue.
