### ISSUE TITLE
can't delete range log items

### ISSUE THREAD

**Issue by wolfgangr** [jliljebl/flowblade#1122]
Please include the following information.
1) Flowblade version (Help->About): git checkout master as of 2023-10-04
2) MLT version (Help->Runtime Environment): 7.18.0
3) Your distribution (Ubuntu, Debian, Mint etc.): deb 10
4) If possible, try to provide step-by-step instructions on how to reproduce the issue. From developer point of view this is the easieast way to understand what is happening.:

- add some range log items
- select one (or multiple?) and hit "Delete selected range" button
- nothing happens
- expected: selected range item would disappear
- same behaviour when I hit right mouse button over log entry and select "Delete" on popup menue

on the console I started flowblade, I can read:
```
Traceback (most recent call last):
  File "/home/wrosner/test/flowblade/flowblade-2.11/flowblade-trunk/Flowblade/medialog.py", line 725, in <lambda>
    delete_button.connect("clicked", lambda w:delete_selected())
  File "/home/wrosner/test/flowblade/flowblade-2.11/flowblade-trunk/Flowblade/medialog.py", line 218, in delete_selected
    PROJECT().remove_from_group(i, delete_events)
  File "/home/wrosner/test/flowblade/flowblade-2.11/flowblade-trunk/Flowblade/projectdata.py", line 320, in remove_from_group
    for i in items:
ValueError: list.remove(x): x not in list
```

possible clue:
my mouse is jittering sometimes.
So accidentially, this way I produced two log entries with the same File Name and Mark in/out values and creation time.
May this cause skd of double key error?
I can edit comment and change star independently, however.
The problem of "indeletability" is not confined to the double entries.

**Comment by wolfgangr** [comment]
update:

I can move items to "Group"
I can delete item from Group or even whole Group.
However, in "All items", they are still there.

on flowblade console, I repeatedly read:

```
(flowblade:29772): Gtk-WARNING **: 23:04:16.166: Duplicate child name in GtkStack: Move Selected Items To Group

(flowblade:29772): Gtk-WARNING **: 23:04:16.223: Duplicate child name in GtkStack: Sort by
```

**Comment by jliljebl** [comment]
Thanks, will look at this.

**Comment by jliljebl** [comment]
Could not reproduce the "failing to delete"  bug, but I did get: 
```
(flowblade:6706): Gtk-WARNING **: 10:30:16.356: Duplicate child name in GtkStack: Sort by

(flowblade:6706): Gtk-WARNING **: 10:30:47.004: Duplicate child name in GtkStack: Move Selected Items To Group

(flowblade:6706): Gtk-WARNING **: 10:30:47.005: Duplicate child name in GtkStack: Move Selected Items To Group

(flowblade:6706): Gtk-WARNING **: 10:30:47.008: Duplicate child name in GtkStack: Sort by

(flowblade:6706): Gtk-WARNING **: 10:30:47.009: Duplicate child name in GtkStack: Sort by
```

Something is wrong here.

**Comment by jliljebl** [comment]
On 2.120.0.4 Flatpak everything works fine, so this is a regression because of moving to use Gtk.Popover menus as step towards Gtk4 transition.

**Comment by jliljebl** [comment]
Will keep this for additional info but I'll handle the (flowblade:6706): *Gtk-WARNING **: 10:30:47.009: Duplicate child name in GtkStack: Sort by* separately.

**Comment by jliljebl** [comment]
This not reproducing, closing.
