### ISSUE TITLE
Broken reset in Position Scale

### ISSUE THREAD

**Issue by schauveau** [jliljebl/flowblade#1147]
I am using the latest trunk but the issue is also present in the Debian package 2.12.0.2-1   

The reset button in the Position Scale filter is causing an exception (see below) that makes all filters disappear from the editor.

The whole filter list becomes corrupted, appears empty and cannot be edited anymore. 
   
This is obviously related to  the Screensize2 used in https://github.com/jliljebl/flowblade/blob/160f1d8db6fb68104d88bafc0d829c82e5fbfe5d/flowblade-trunk/Flowblade/res/filters/filters.xml#L1092

Replacing it with a fake dimension (e.g. 320 200) makes the issue disappear on newly created Position Scale filters but not on old ones. 

```
Traceback (most recent call last):
  File "/home/chauveau/git/flowblade/flowblade-trunk/Flowblade/cairoarea.py", line 92, in _button_press_event
    self.press_func(event)
  File "/home/chauveau/git/flowblade/flowblade-trunk/Flowblade/tlinewidgets.py", line 1480, in _press_event
    self.double_click_listener(get_frame(event.x), event.x, event.y)
  File "/home/chauveau/git/flowblade/flowblade-trunk/Flowblade/editevent.py", line 460, in tline_canvas_double_click
    updater.open_clip_in_effects_editor(data)
  File "/home/chauveau/git/flowblade/flowblade-trunk/Flowblade/updater.py", line 623, in open_clip_in_effects_editor
    clipeffectseditor.set_clip(clip, track, index)
  File "/home/chauveau/git/flowblade/flowblade-trunk/Flowblade/clipeffectseditor.py", line 455, in set_clip
    update_stack(clip, track, clip_index)
  File "/home/chauveau/git/flowblade/flowblade-trunk/Flowblade/clipeffectseditor.py", line 598, in update_stack
    new_stack = ClipFilterStack(clip, track, clip_index)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chauveau/git/flowblade/flowblade-trunk/Flowblade/clipeffectseditor.py", line 299, in __init__
    edit_panel, kf_editors = _get_filter_panel(clip, filter_object, filter_index, track, clip_index)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chauveau/git/flowblade/flowblade-trunk/Flowblade/clipeffectseditor.py", line 748, in _get_filter_panel
    editor_row = propertyeditorbuilder.get_editor_row(ep)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chauveau/git/flowblade/flowblade-trunk/Flowblade/propertyeditorbuilder.py", line 110, in get_editor_row
    return create_func(editable_property)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chauveau/git/flowblade/flowblade-trunk/Flowblade/propertyeditorbuilder.py", line 1225, in <lambda>
    FILTER_RECT_GEOM_EDITOR: lambda ep : _get_filter_rect_geom_editor(ep)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chauveau/git/flowblade/flowblade-trunk/Flowblade/propertyeditorbuilder.py", line 991, in _get_filter_rect_geom_editor
    return keyframeeditor.FilterRectGeometryEditor(ep)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chauveau/git/flowblade/flowblade-trunk/Flowblade/keyframeeditor.py", line 1713, in __init__
    self.init_geom_gui(editable_property)
  File "/home/chauveau/git/flowblade/flowblade-trunk/Flowblade/keyframeeditor.py", line 1723, in init_geom_gui
    self.geom_kf_edit.set_keyframes(editable_property.value, editable_property.get_in_value)
  File "/home/chauveau/git/flowblade/flowblade-trunk/Flowblade/keyframeeditcanvas.py", line 378, in set_keyframes
    self.keyframes = self.keyframe_parser(keyframes_str, out_to_in_func)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chauveau/git/flowblade/flowblade-trunk/Flowblade/propertyparse.py", line 315, in rect_keyframes_value_string_to_geom_kf_array
    source_rect = [int(x), int(y), int(w), int(h)] #x,y,width,height
                                   ^^^^^^
ValueError: invalid literal for int() with base 10: 'Screensize2'
```

**Comment by jliljebl** [comment]
Thanks, confirmed, will look into this. The editor for this is only one of its type, so there needs to be some special casing added somewhere fix this.

**Comment by schauveau** [comment]
Since you are on that, could you also make SCREENSIZE_WIDTH and SCREENSIZE_HEIGHT work for the default value?
That would allow for better defaults in the Perspective filter.

**Comment by jliljebl** [comment]
I seems to remember this being a very strange issue somehow, but I'll give it another look.

**Comment by jliljebl** [comment]
Fixed the bug, I just had forgot to do value replace for properties needing it when doing for editor re-init.

**Comment by jliljebl** [comment]
Tried the Perspective Filter SCREENSIZE_WIDTH, SCREENSIZE_HEIGHT issue, now I at least got a error message which I don't remember getting when I previously had problem with this. I'll give this more work, but immediate results probably wont be coming.

```
[perspective @ 0x7f56e2afa200] [Eval @ 0x7f56f5407770] Invalid chars 'x720_WIDTH' at the end of expression '1280x720_WIDTH'
[perspective @ 0x7f56e2afa200] Failed to configure input pad on perspective
```

**Comment by jliljebl** [comment]
Got the Perspective Filter SCREENSIZE_WIDTH, SCREENSIZE_HEIGH thing fixed too, code was just a bit naive , here: 
https://github.com/jliljebl/flowblade/commit/e5a1ed740cb46a255d5984000abe796f263255d6
