### ISSUE TITLE
Crashes on startup after new install

### ISSUE THREAD

**Issue by pulpocaminante** [jliljebl/flowblade#1150]
Please include the following information.
1) Flowblade version (Help->About): 2.12-1
2) MLT version (Help->Runtime Environment): 7.22.0-3
3) Your distribution and desktop environment(Ubuntu/Unity, Debian/KDE, Mint/Cinnamon etc.): Arch & Sway
4) X11 or Wayland: Wayland
5) If possible, try to provide step-by-step instructions on how to reproduce the issue. From developer point of view this is the easieast way to understand what is happening.:

Installed via pacman, crash on startup:
```

Player initialized with profile:  HD 1080p 30 fps
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/Flowblade/app.py", line 353, in on_activate
    launch_player()
  File "/usr/lib/python3.11/site-packages/Flowblade/app.py", line 553, in launch_player
    editorstate.player.set_sdl_xwindow(gui.tline_display)
  File "/usr/lib/python3.11/site-packages/Flowblade/mltplayer.py", line 119, in set_sdl_xwindow
    os.putenv('SDL_WINDOWID', str(widget.get_window().get_xid()))
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'GdkWaylandWindow' object has no attribute 'get_xid'. Did you mean: 'get_width'?
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/Flowblade/utilsgtk.py", line 57, in _update
    self.action(self.data)
  File "/usr/lib/python3.11/site-packages/Flowblade/mltplayer.py", line 318, in _ticker_event
    if (self.consumer.is_stopped() or self.producer.get_speed() == 0):
        ^^^^^^^^^^^^^
AttributeError: 'Player' object has no attribute 'consumer'
GPU test results {'NVENC H.264 High Profile / .mp4': -11, 'NVENC HEVC / .mp4': -11, 'NVENC HEVC HDR / .mp4': -11, 'VAAPI H.264 / .mp4': -11}
                                                                                                                             
amnesia git:master*                                                                                                     /5.3s
(base) ❯ 

```

**Comment by jliljebl** [comment]
Application needs to be started with command:

```
SDL12COMPAT_NO_QUIT_VIDEO=1 GDK_BACKEND=x11 SDL_VIDEODRIVER=x11 /usr/bin/flowblade
```

or something similar depending on where Floblade is installed on your system, related F.A.Q item here:

https://github.com/jliljebl/flowblade/blob/master/flowblade-trunk/docs/FAQ.md#wayland
