### ISSUE TITLE
Problems with Paths - Possibly Corrupted Project after Upgrade

### ISSUE THREAD

**Issue by pragmaware** [jliljebl/flowblade#1153]
Flowblade version : 2.12.0.2
MLT version : 7.18.0
Distribution : kubuntu + KDE
X11 or Wayland: X11

The editor is unable to save the project.
```
Saving project...
Traceback (most recent call last):
  File "/usr/share/flowblade/Flowblade/editorwindow.py", line 805, in <lambda>
    ('Save', None, _('_Save'), '<control>S', None, lambda a:projectaction.save_project()),
                                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/flowblade/Flowblade/projectaction.py", line 550, in save_project
    _save_project_in_last_saved_path()
  File "/usr/share/flowblade/Flowblade/projectaction.py", line 559, in _save_project_in_last_saved_path
    projectdatavault.project_saved( PROJECT().last_save_path)
  File "/usr/share/flowblade/Flowblade/projectdatavault.py", line 210, in project_saved
    savefiles_path = get_project_data_folder() + SAVE_FILES_FILE
                     ~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```

Also waveforms aren't displayed anymore when adding clips to the timeline.

```
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/usr/share/flowblade/Flowblade/audiowaveformrenderer.py", line 157, in run
    self.process = subprocess.Popen([sys.executable, respaths.LAUNCH_DIR + "flowbladeaudiorender", \
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.11/subprocess.py", line 1883, in _execute_child
    self.pid = _fork_exec(
               ^^^^^^^^^^^
TypeError: expected str, bytes or os.PathLike object, not NoneType

```

My impression is that it has to do something with paths and it started happening after I upgraded flowblade
via ubuntu package.

**Comment by jliljebl** [comment]
Thanks for the report. I've been quite busy for that past few weeks, will try to look into this at end of the week or next week.

**Comment by jliljebl** [comment]
> The editor is unable to save the project.

>  File "/usr/share/flowblade/Flowblade/projectdatavault.py", line 210, in project_saved
    savefiles_path = get_project_data_folder() + SAVE_FILES_FILE
                     ~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

Ok, I found the issue here. I only affect when saving with *CTRL + S* and it should still save it but crash after that. I'll need to do some testing but the fix should be relatively easy.

**Comment by jliljebl** [comment]
I got both fixed with one additional issue found while working with this. I'll keep this open for a bit and to do some more testing.

**Comment by jliljebl** [comment]
Did some additional tests and everything working now. Thanks for the report, missed this on development. Release 2.24 with this fix is coming next week, unless some unexpected problems arise.
