### ISSUE TITLE
Wayland flowblade void linux crash

### ISSUE THREAD

**Issue by narodnik** [jliljebl/flowblade#1164]
Tried both the git and repo version with the same result:

```
$ flowblade
FLOWBLADE MOVIE EDITOR 2.16.3
-----------------------------
Launch script dir: /usr/bin
Running from installation...
modules path: /usr/share/flowblade/Flowblade
MLT found, version: 7.24.0
/usr/share/flowblade/Flowblade/keyevents.py:564: SyntaxWarning: invalid escape sequence '\s'
  action = _secondary_dict[''.join(sorted(re.sub('[\s]','',modifier.lower())))]
/usr/share/flowblade/Flowblade/keyevents.py:567: SyntaxWarning: invalid escape sequence '\s'
  action = _secondary_dict[''.join(sorted(re.sub('[\s]','','Any'.lower())))]
/usr/share/flowblade/Flowblade/shortcuts.py:144: SyntaxWarning: invalid escape sequence '\s'
  _modifier_dict[''.join(sorted(re.sub('[\s]','','None'.lower())))] = event.get('code')
/usr/share/flowblade/Flowblade/shortcuts.py:146: SyntaxWarning: invalid escape sequence '\s'
  _modifier_dict[''.join(sorted(re.sub('[\s]','',event.get('modifiers').lower())))] = event.get('code')
Application version: 2.16.3
OS: Void Linux
Python 3.12.4 (main, Jun  9 2024, 22:05:49) [GCC 13.2.0]
GTK+ version: 3.24.42
Locale: en_US
Translations at /usr/share/locale were not found, using program root directory translations.
Use OS locale language.
Valid shortcut files found: ['flowblade.xml', 'premiere.xml']
Keyboard shortcuts file: flowblade.xml
Using Full Screen size for layout: 11520 x 2160
Small height: False
Small width: False
Detecting environment...
---
video_codecs:
  - a64multi
  - a64multi5
  - alias_pix
  - amv
  - apng
  - asv1
  - asv2
  - avrp
  - avui
  - ayuv
  - bitpacked
  - bmp
  - cfhd
  - cinepak
  - cljr
  - dnxhd
  - dpx
  - dvvideo
  - exr
  - ffv1
  - ffvhuff
  - fits
  - flashsv
  - flashsv2
  - flv
  - gif
  - h261
  - h263
  - h263p
  - huffyuv
  - jpeg2000
  - jpegls
  - ljpeg
  - magicyuv
  - mjpeg
  - mpeg1video
  - mpeg2video
  - mpeg4
  - msmpeg4v2
  - msmpeg4
  - msvideo1
  - pam
  - pbm
  - pcx
  - pfm
  - pgm
  - pgmyuv
  - phm
  - png
  - ppm
  - prores
  - prores_aw
  - prores_ks
  - qoi
  - qtrle
  - r10k
  - r210
  - rawvideo
  - roqvideo
  - rpza
  - rv10
  - rv20
  - sgi
  - smc
  - snow
  - speedhq
  - sunrast
  - svq1
  - targa
  - tiff
  - utvideo
  - v210
  - v308
  - v408
  - v410
  - vbn
  - vc2
  - wbmp
  - wrapped_avframe
  - wmv1
  - wmv2
  - xbm
  - xface
  - xwd
  - y41p
  - yuv4
  - zlib
  - zmbv
  - hdr
  - libaom-av1
  - libsvtav1
  - libtheora
  - libvpx
  - libvpx-vp9
  - libwebp_anim
  - libwebp
  - libx264
  - libx264rgb
  - libx265
  - libxvid
  - h263_v4l2m2m
  - av1_nvenc
  - av1_qsv
  - h264_nvenc
  - h264_qsv
  - h264_v4l2m2m
  - h264_vaapi
  - hevc_nvenc
  - hevc_qsv
  - hevc_v4l2m2m
  - hevc_vaapi
  - mjpeg_qsv
  - mjpeg_vaapi
  - mpeg2_qsv
  - mpeg2_vaapi
  - mpeg4_v4l2m2m
  - vp8_v4l2m2m
  - vp8_vaapi
  - vp9_vaapi
  - vp9_qsv
  - vnull
...
---
audio_codecs:
  - comfortnoise
  - s302m
  - aac
  - ac3
  - ac3_fixed
  - alac
  - aptx
  - aptx_hd
  - dca
  - dfpwm
  - eac3
  - flac
  - g723_1
  - mlp
  - mp2
  - mp2fixed
  - nellymoser
  - opus
  - real_144
  - sbc
  - sonic
  - sonicls
  - truehd
  - tta
  - vorbis
  - wavpack
  - wmav1
  - wmav2
  - pcm_alaw
  - pcm_bluray
  - pcm_dvd
  - pcm_f32be
  - pcm_f32le
  - pcm_f64be
  - pcm_f64le
  - pcm_mulaw
  - pcm_s8
  - pcm_s8_planar
  - pcm_s16be
  - pcm_s16be_planar
  - pcm_s16le
  - pcm_s16le_planar
  - pcm_s24be
  - pcm_s24daud
  - pcm_s24le
  - pcm_s24le_planar
  - pcm_s32be
  - pcm_s32le
  - pcm_s32le_planar
  - pcm_s64be
  - pcm_s64le
  - pcm_u8
  - pcm_u16be
  - pcm_u16le
  - pcm_u24be
  - pcm_u24le
  - pcm_u32be
  - pcm_u32le
  - pcm_vidc
  - roq_dpcm
  - adpcm_adx
  - adpcm_argo
  - g722
  - g726
  - g726le
  - adpcm_ima_amv
  - adpcm_ima_alp
  - adpcm_ima_apm
  - adpcm_ima_qt
  - adpcm_ima_ssi
  - adpcm_ima_wav
  - adpcm_ima_ws
  - adpcm_ms
  - adpcm_swf
  - adpcm_yamaha
  - libmp3lame
  - libopus
  - libspeex
  - libvorbis
  - anull
...
---
formats:
  - a64
  - ac3
  - adts
  - adx
  - aiff
  - alp
  - amr
  - amv
  - apm
  - apng
  - aptx
  - aptx_hd
  - argo_asf
  - argo_cvg
  - asf
  - ass
  - ast
  - asf_stream
  - au
  - avi
  - avif
  - avm2
  - avs2
  - avs3
  - bit
  - caf
  - cavsvideo
  - codec2
  - codec2raw
  - crc
  - dash
  - data
  - daud
  - dfpwm
  - dirac
  - dnxhd
  - dts
  - dv
  - eac3
  - f4v
  - ffmetadata
  - fifo
  - fifo_test
  - filmstrip
  - fits
  - flac
  - flv
  - framecrc
  - framehash
  - framemd5
  - g722
  - g723_1
  - g726
  - g726le
  - gif
  - gsm
  - gxf
  - h261
  - h263
  - h264
  - hash
  - hds
  - hevc
  - hls
  - ico
  - ilbc
  - image2
  - image2pipe
  - ipod
  - ircam
  - ismv
  - ivf
  - jacosub
  - kvag
  - latm
  - lrc
  - m4v
  - md5
  - matroska
  - matroska
  - microdvd
  - mjpeg
  - mlp
  - mmf
  - mov
  - mp2
  - mp3
  - mp4
  - mpeg
  - vcd
  - mpeg1video
  - dvd
  - svcd
  - mpeg2video
  - vob
  - mpegts
  - mpjpeg
  - mxf
  - mxf_d10
  - mxf_opatom
  - null
  - nut
  - obu
  - oga
  - ogg
  - ogv
  - oma
  - opus
  - alaw
  - mulaw
  - vidc
  - f64be
  - f64le
  - f32be
  - f32le
  - s32be
  - s32le
  - s24be
  - s24le
  - s16be
  - s16le
  - s8
  - u32be
  - u32le
  - u24be
  - u24le
  - u16be
  - u16le
  - u8
  - psp
  - rawvideo
  - rm
  - roq
  - rso
  - rtp
  - rtp_mpegts
  - rtsp
  - sap
  - sbc
  - scc
  - film_cpk
  - segment
  - stream_segment,ssegment
  - smjpeg
  - smoothstreaming
  - sox
  - spx
  - spdif
  - srt
  - streamhash
  - sup
  - swf
  - tee
  - 3g2
  - 3gp
  - mkvtimestamp_v2
  - truehd
  - tta
  - ttml
  - uncodedframecrc
  - vc1
  - vc1test
  - voc
  - w64
  - wav
  - webm
  - webm_dash_manifest
  - webm_chunk
  - webp
  - webvtt
  - wsaud
  - wtv
  - wv
  - yuv4mpegpipe
  - alsa
  - fbdev
  - oss
  - pulse
  - sdl,sdl2
  - sndio
  - video4linux2,v4l2
  - xv
...
MLT detection succeeded, 182 formats, 121 video codecs and 80 audio codecs found.
678 MLT services found.
Loading render profiles...
ffmpeg version 6.0.1 Copyright (c) 2000-2023 the FFmpeg developers
built with gcc 13.2.0 (GCC)
configuration: --prefix=/usr --disable-debug --enable-gpl --enable-gnutls --disable-stripping --enable-libcdio --enable-version3 --enable-runtime-cpudetect --enable-libmp3lame --enable-libvorbis --enable-libxvid --enable-libx264 --enable-libvpx --enable-libtheora --enable-shared --enable-static --enable-libxcb --enable-libpulse --enable-libfreetype --enable-libmodplug --enable-libspeex --enable-libcelt --enable-libass --enable-libopus --enable-librtmp --enable-libjack --disable-libopencore_amrnb --disable-libopencore_amrwb --disable-libopenjpeg --enable-libbluray --enable-postproc --enable-opencl --enable-libvmaf --enable-libx265 --enable-libv4l2 --enable-libaom --enable-libbs2b --enable-libvidstab --enable-libdav1d --enable-libsrt --enable-librist --enable-libwebp --enable-vulkan --enable-libdrm --enable-vaapi --enable-vdpau --disable-libzimg --disable-libmysofa --enable-libvpl --enable-libsvtav1 --enable-nvenc --enable-nvdec
libavutil      58.  2.100 / 58.  2.100
libavcodec     60.  3.100 / 60.  3.100
libavformat    60.  3.100 / 60.  3.100
libavdevice    60.  1.100 / 60.  1.100
libavfilter     9.  3.100 /  9.  3.100
libswscale      7.  1.100 /  7.  1.100
libswresample   4. 10.100 /  4. 10.100
libpostproc    57.  1.100 / 57.  1.100
['ffmpeg', '-version']
return code: 0
ffmpeg CLI available
Loading filters...
MLT service frei0r.alpha0ps_alphagrad not found.
MLT service frei0r.alpha0ps_alphaspot not found.
MLT service frei0r.alpha0ps_alpha0ps not found.
MLT service rbpitch not found.
MLT service rbpitch not found.
Loading transitions...
G'MIC found
Player initialized with profile:  HD 1080p 30 fps
Traceback (most recent call last):
  File "/usr/share/flowblade/Flowblade/app.py", line 358, in on_activate
    launch_player()
  File "/usr/share/flowblade/Flowblade/app.py", line 570, in launch_player
    editorstate.player.set_sdl_xwindow(gui.tline_display)
  File "/usr/share/flowblade/Flowblade/mltplayer.py", line 89, in set_sdl_xwindow
    os.putenv('SDL_WINDOWID', str(widget.get_window().get_xid()))
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'GdkWaylandWindow' object has no attribute 'get_xid'. Did you mean: 'get_width'?
Traceback (most recent call last):
  File "/usr/share/flowblade/Flowblade/editorwindow.py", line 133, in <lambda>
    self.window.connect("window-state-event", lambda w, e:updater.refresh_player(e))
                                                          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/flowblade/Flowblade/updater.py", line 121, in refresh_player
    PLAYER().refresh()
  File "/usr/share/flowblade/Flowblade/mltplayer.py", line 106, in refresh
    self.consumer.stop()
    ^^^^^^^^^^^^^
AttributeError: 'Player' object has no attribute 'consumer'
GPU test results {'NVENC H.264 High Profile / .mp4': -11, 'NVENC HEVC / .mp4': -11, 'NVENC HEVC HDR / .mp4': -11, 'VAAPI H.264 / .mp4': 0}```

**Comment by jliljebl** [comment]
See F.A.Q., you need to define Flowblade as using XWayland.
