### ISSUE TITLE
Projects are not portable

### ISSUE THREAD

**Issue by TheKilroy** [jliljebl/flowblade#1168]
1) Flowblade version (Help->About): 2.16.3
2) MLT version (Help->Runtime Environment): 7.4.0
3) Your distribution and desktop environment(Ubuntu/Unity, Debian/KDE, Mint/Cinnamon etc.): Ubuntu 22.04 LTS
4) X11 or Wayland: X11

I have an external Harddisk with my projects. If I move the HD to another PC running the same version OS and Flowblade I get references to the ~/.local/share folder and .config/flowblade folder which result in an IO error on saving the project.

In my case the file "~/.local/share/flowblade/projectsdata/ff8bdec9589faed3e93af07a214c39e3/savefiles" was referenced but folder was not existing.

```
Sep  2 11:09:36 Frank-NB gnome-shell[7572]: DING: During handling of the above exception, another exception occurred:
Sep  2 11:09:36 Frank-NB gnome-shell[7572]: DING: Traceback (most recent call last):
Sep  2 11:09:36 Frank-NB gnome-shell[7572]: DING:   File "/opt/flowblade/Flowblade/app.py", line 1085, in _shutdown_dialog_callback
Sep  2 11:09:36 Frank-NB gnome-shell[7572]: DING:     projectdatavault.project_saved(editorstate.PROJECT().last_save_path)
Sep  2 11:09:36 Frank-NB gnome-shell[7572]: DING:   File "/opt/flowblade/Flowblade/projectdatavault.py", line 217, in project_saved
Sep  2 11:09:36 Frank-NB gnome-shell[7572]: DING:     savefiles_list = utils.unpickle(savefiles_path)
Sep  2 11:09:36 Frank-NB gnome-shell[7572]: DING:   File "/opt/flowblade/Flowblade/utils.py", line 589, in unpickle
Sep  2 11:09:36 Frank-NB gnome-shell[7572]: DING:     f = open(path, "rb")
Sep  2 11:09:36 Frank-NB gnome-shell[7572]: DING: FileNotFoundError: [Errno 2] Datei oder Verzeichnis nicht gefunden: '/home/frank/.local/share/flowblade/projectsdata/65680a28d05885cc1311322167d3cf3d/savefiles'
Sep  2 11:09:57 Frank-NB systemd[7208]: Started VTE child process 79299 launched by gnome-terminal-server process 30621.

```

Would be nice to get around that problem somehow.

Thank you for that awesome program.

**Comment by jliljebl** [comment]
I thought there was a procedure to make this work already with existing features, but when testing it found a regression. *(The bug is in feature in Project->Project Data->Create Clone Project in another Data Store)*

Once that is fixed for next release, I'll post here the procedure, and ask you if you could confirm that it works. So there is some hope to get this already for next version 2.18. 

Anyway, we will be also making fully archivable projects in the future where you can create an folder that holds all data for a project, save that and later import data from that folder to create a working project on *any* machine running equal or later version of the application. That feature can also be used to do what is requested here, but that feature will come earliest for 2.20.

I'm unusually labeling this with both 'bug' for the mentioned bug and 'in feature queue' the planned archiving feature.

**Comment by TheKilroy** [comment]
Awesome news. Thank you.
