### ISSUE TITLE
clips copied from other project cannot be exported to tools. 

### ISSUE THREAD

**Issue by stingpie** [jliljebl/flowblade#1174]
Please include the following information.
1) Flowblade version (Help->About): 2.16.3
2) MLT version (Help->Runtime Environment): 7.28.0
3) Your distribution and desktop environment(Ubuntu/Unity, Debian/KDE, Mint/Cinnamon etc.): arch
4) X11 or Wayland: x11
5) If possible, try to provide step-by-step instructions on how to reproduce the issue. From developer point of view this is the easieast way to understand what is happening.:
create two projects, with different media files. cut a clip out of the second project, and copy it into the first one. Right click on the clip, select export to tool>reverser. Nothing will happen. In the terminal, python will throw an exception: 

Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/Flowblade/toolsintegration.py", line 70, in export_callback
    new_instance.do_export()
  File "/usr/lib/python3.12/site-packages/Flowblade/toolsintegration.py", line 134, in do_export
    media_file.mark_in = clip.clip_in
    ^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'mark_in'

**Comment by jliljebl** [comment]
> create two projects, with different media files. cut a clip out of the second project, and copy it into the first one. Right click on the clip, select export to tool>reverser. Nothing will happen. In the terminal, python will throw an exception:

For 2.18 we replaced *export to tool>reverse* functionality with direct timeline rendering, slowmo/reverse clips are rendered directly onto timeline without being opened in a tool and creating new Media Items and that seems to work.

> Traceback (most recent call last):
File "/usr/lib/python3.12/site-packages/Flowblade/toolsintegration.py", line 70, in export_callback
new_instance.do_export()
File "/usr/lib/python3.12/site-packages/Flowblade/toolsintegration.py", line 134, in do_export
media_file.mark_in = clip.clip_in
^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'mark_in'

I'll still need to try to fix this issue because we need to have imported Media Items be indistinguishable from Media Items created in project so that we don't hit any issues like you describe here, even if this seems to be working with new Timeline slow motion/reverse clips. 

I'll add back the possibility to open clip in G'Mic tool to test this. Maybe that really was a useful feature that got dropped for 2.18 with too little consideration given.
