### ISSUE TITLE
1.2 does not work on Ubuntu 14.04

### ISSUE THREAD

**Issue by jliljebl** [jliljebl/flowblade#170]
This is not visible on later versions, but needs to be fixed any way.

We've gotten this stack trace from several sources. 

TypeError: Couldn't find conversion for foreign struct 'cairo.Context'
Traceback (most recent call last):
  File "/usr/share/flowblade/Flowblade/editorwindow.py", line 151, in <lambda>
    ('Quit', None, _('_Quit'), '<control>Q', None, lambda a:app.shutdown()),
  File "/usr/share/flowblade/Flowblade/app.py", line 698, in shutdown
    dialogs.exit_confirm_dialog(_shutdown_dialog_callback, get_save_time_msg(), gui.editor_window.window, editorstate.PROJECT().name)
  File "/usr/share/flowblade/Flowblade/app.py", line 704, in get_save_time_msg
    return _("Project has not been saved since it was opened.")
  File "/usr/lib/python2.7/gettext.py", line 220, in ugettext
    return unicode(message)
TypeError: Couldn't find conversion for foreign struct 'cairo.Context'
Traceback (most recent call last):
  File "/usr/share/flowblade/Flowblade/editorwindow.py", line 151, in <lambda>
    ('Quit', None, _('_Quit'), '<control>Q', None, lambda a:app.shutdown()),
  File "/usr/share/flowblade/Flowblade/app.py", line 698, in shutdown
    dialogs.exit_confirm_dialog(_shutdown_dialog_callback, get_save_time_msg(), gui.editor_window.window, editorstate.PROJECT().name)
  File "/usr/share/flowblade/Flowblade/app.py", line 704, in get_save_time_msg
    return _("Project has not been saved since it was opened.")
  File "/usr/lib/python2.7/gettext.py", line 220, in ugettext
    return unicode(message)
TypeError: Couldn't find conversion for foreign struct 'cairo.Context'
Traceback (most recent call last):
  File "/usr/share/flowblade/Flowblade/cairoarea.py", line 113, in _enter_notify_event
    self.enter_notify_func(event)
  File "/usr/share/flowblade/Flowblade/editorwindow.py", line 1005, in tline_cursor_enter
    self.set_cursor_to_mode()
  File "/usr/share/flowblade/Flowblade/editorwindow.py", line 940, in set_cursor_to_mode
    self.set_tline_cursor(editorstate.EDIT_MODE())
  File "/usr/share/flowblade/Flowblade/editorwindow.py", line 950, in set_tline_cursor
    cursor = Gdk.Cursor.new_from_surface(display, INSERTMOVE_CURSOR, 0, 0)
KeyError: 'could not find foreign type Surface'

**Comment by jliljebl** [comment]
This is going wontfix, 1.0 will be the recommended Flowblade version for Ubuntu 14.04, and no furher bug reports will be accepted for Ubuntu 14.04. This is not a Flowblade bug _perse_, Flowblade uses some new GTK3 features and it appears that these are not working on Ubuntu14.04.
