### ISSUE TITLE
Titler Sometimes Freaks Out

### ISSUE THREAD

**Issue by benrob0329** [jliljebl/flowblade#312]
Whilst using the titler, the text will sometimes disappear, though with some fiddling you can sometimes get it to reappear momentarily.

**Comment by jliljebl** [comment]
Do you get some error messages when the bug happens?

1. Open terminal application.
2. Start Flowblade with command "flowblade"
3. Work on Titler until you hit the bug.
4. Is there some text displayed on terminal? If so, please copy paste it here.

Getting some error messages would be very helpful on fixing this.

**Comment by benrob0329** [comment]
```
Traceback (most recent call last):
  File "/usr/share/flowblade/Flowblade/cairoarea.py", line 81, in _draw_event
    self._draw_func(None, cr, (a.x, a.y, a.width, a.height)) # 'None' is event object that was used to pass through here. Can be removed.
  File "/usr/share/flowblade/Flowblade/vieweditor/vieweditor.py", line 241, in _draw
    editorlayer.draw(cr, self.write_out_layers, self.draw_overlays)
  File "/usr/share/flowblade/Flowblade/vieweditor/vieweditorlayer.py", line 240, in draw
    rotation = self.edit_point_shape.get_first_two_points_rotation_angle()
  File "/usr/share/flowblade/Flowblade/vieweditor/vieweditorshape.py", line 202, in get_first_two_points_rotation_angle
    return 2 * math.pi - viewgeom.get_angle_in_rad(p1, anchor, p2)
  File "/usr/share/flowblade/Flowblade/vieweditor/viewgeom.py", line 97, in get_angle_in_rad
    return math.acos(angle_cos)
ValueError: math domain error
Save project autosave_09dcb4a8797a43a9b2f63aa373e4b977
Traceback (most recent call last):
  File "/usr/share/flowblade/Flowblade/cairoarea.py", line 81, in _draw_event
    self._draw_func(None, cr, (a.x, a.y, a.width, a.height)) # 'None' is event object that was used to pass through here. Can be removed.
  File "/usr/share/flowblade/Flowblade/vieweditor/vieweditor.py", line 241, in _draw
    editorlayer.draw(cr, self.write_out_layers, self.draw_overlays)
  File "/usr/share/flowblade/Flowblade/vieweditor/vieweditorlayer.py", line 240, in draw
    rotation = self.edit_point_shape.get_first_two_points_rotation_angle()
  File "/usr/share/flowblade/Flowblade/vieweditor/vieweditorshape.py", line 202, in get_first_two_points_rotation_angle
    return 2 * math.pi - viewgeom.get_angle_in_rad(p1, anchor, p2)
  File "/usr/share/flowblade/Flowblade/vieweditor/viewgeom.py", line 97, in get_angle_in_rad
    return math.acos(angle_cos)
ValueError: math domain error
```

**Comment by jliljebl** [comment]
Ok thanks, this helps. 

I have not reproduced this on my system. Is there some particular action that triggers this?

**Comment by benrob0329** [comment]
Try putting a lot of text on screen, sizing it up, and moving it around.

**Comment by jliljebl** [comment]
Ok, I tried reproducing this but I was unable to. Your error print out is anyway proof that something is happening, so I will leave it open for now, and maybe at some point try to figure out a logival fix to it.

**Comment by dvdlvr** [comment]
@benrob0329
I tried reproducing this but couldn't do it either.
What would help is if you could do the following:
1) Tell us what version of Flowblade you are using
2) Tell us what project profile you are using
3) Create a title that gives the crash on your system and do a 'save layers' then attach the saved file to this bug
4) The crash is likely to be linked to a specific position on the screen. Can you try a bit more to see where you move the title when the crash occurs? Maybe give us the x + y values - or at least an approximation - and the direction you were moving in (left, right, up, down)

Thanks.

**Comment by benrob0329** [comment]
Strange, it doesn't seem to want to do it now, perhaps it was the system configuration (as I am now on a different install)

Closing as it seems to be system related.
