### ISSUE TITLE
volume filter keyframing does not work anymore in 1.12

### ISSUE THREAD

**Issue by empee0** [jliljebl/flowblade#356]
Hi,
when I try to add an audio volume fllter, there are no settings available in the filter tab, neither values nor keyframes get visable.  Here is the traceback I get when trying to edit the volume filter:

Traceback (most recent call last):
  File "/usr/share/flowblade/Flowblade/clipeffectseditor.py", line 225, in <lambda>
    widgets.effect_stack_view = guicomponents.FilterSwitchListView(lambda ts: effect_selection_changed(), 
  File "/usr/share/flowblade/Flowblade/clipeffectseditor.py", line 471, in effect_selection_changed
    clip_index)
  File "/usr/share/flowblade/Flowblade/propertyedit.py", line 107, in get_filter_editable_properties
    ep = _create_editable_property(appconsts.PROP_EXPRESSION, args_str, params)
  File "/usr/share/flowblade/Flowblade/propertyedit.py", line 126, in _create_editable_property
    ep = creator_func(params)
  File "/usr/share/flowblade/Flowblade/propertyedit.py", line 817, in <lambda>
    MULTIPART_KEYFRAME_HCS: lambda params : MultipartKeyFrameProperty(params),
  File "/usr/share/flowblade/Flowblade/propertyedit.py", line 730, in __init__
    clip, filter_index, property, property_index, args_str = paramsg
NameError: global name 'paramsg' is not defined
 
Version 1.10 works correctly

Could you have a look at this?
Thanks !
Mario

**Comment by jliljebl** [comment]
Confirmed. Jesus f***** s***. There is some extra g letter from some where, should be:

    clip, filter_index, property, property_index, args_str = params

Will fix, and now I need to push a new .deb.

**Comment by empee0** [comment]
thanks!

**Comment by empee0** [comment]
jepp after removing the trailing g evrything works fine :-)

**Comment by jliljebl** [comment]
New .deb now available and fixed in repo.

**Comment by empee0** [comment]
I can confirm that master works fine. Thanks for the quick help!!

**Comment by jliljebl** [comment]
Fixed in 1.14, closing.
