### ISSUE TITLE
Markers cannot handle Unicode characters

### ISSUE THREAD

**Issue by dvdlvr** [jliljebl/flowblade#377]
When entering a marker with a unicode label there is an error and the markers don't show up on the dropdown list of markers.
Traceback (most recent call last):
  File "flowblade/flowblade-trunk/Flowblade/cairoarea.py", line 93, in _button_press_event
    self.press_func(event)
  File "flowblade/flowblade-trunk/Flowblade/guicomponents.py", line 2421, in _press_event
    self.callback(self.widget, event)
  File "flowblade/flowblade-trunk/Flowblade/tlineaction.py", line 1097, in marker_menu_lauch_pressed
    guicomponents.get_markers_popup_menu(event, _marker_menu_item_activated)
  File "flowblade/flowblade-trunk/Flowblade/guicomponents.py", line 2093, in get_markers_popup_menu
    menu.add(_get_menu_item(_(item_str), callback, str(i) ))
  File "/usr/lib/python2.7/gettext.py", line 295, in ugettext
    return unicode(message)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc5 in position 12: ordinal not in range(128)

This was after using the ņ character in a marker.

**Comment by jliljebl** [comment]
Confirmed and fixed. This was fixed by removing the incorrect attempt to translate user provided marker names.
