### ISSUE TITLE
Hard to recreate bug - hang while sending mouse events during project reload?

### ISSUE THREAD

**Issue by cefn** [jliljebl/flowblade#497]
Please include the following information.
1) Flowblade version (Help->About): 1.16.0 (flatpak version)
2) MLT version (Help->Runtime Environment):6.6.0
3) Your distribution (Ubuntu, Debian, Mint etc.): Lubuntu 17.10

Thought it would be worth sharing this hard-crash which occurred with Flowblade as it may be possible to understand the context it occurred from the stack trace itself, although I found it hard to recreate.

I ran the program like...

```
flatpak run io.github.jliljebl.Flowblade 2>&1 | grep -v "underrun occurred"
```

Having dragged in an image and trying to test responsiveness while exploring https://github.com/jliljebl/flowblade/issues/496

...I dragged a video file into the bin which had a different file type so it prompted me to change the project profile. I accepted the change, and may have clicked on the window or moved the mouse over the window while it was resaving/reloading. The program then hung up with the following sent to the console.

```
Loading Project, SAVEFILE_VERSION: 5
Traceback (most recent call last):
  File "/app/share/flowblade/Flowblade/cairoarea.py", line 114, in _motion_notify_event
    self.motion_notify_func(x, y, state)
  File "/app/share/flowblade/Flowblade/tlinewidgets.py", line 1368, in _motion_notify_event
    self.set_pointer_context(x, y)
  File "/app/share/flowblade/Flowblade/tlinewidgets.py", line 1396, in set_pointer_context
    current_pointer_context = self.get_pointer_context(x, y)
  File "/app/share/flowblade/Flowblade/tlinewidgets.py", line 1409, in get_pointer_context
    hit_compositor = compositor_hit(frame, y, current_sequence().compositors)
  File "/app/share/flowblade/Flowblade/editorstate.py", line 145, in current_sequence
    return project.c_seq
AttributeError: Project instance has no attribute 'c_seq'
Traceback (most recent call last):
  File "/app/share/flowblade/Flowblade/cairoarea.py", line 114, in _motion_notify_event
    self.motion_notify_func(x, y, state)
  File "/app/share/flowblade/Flowblade/tlinewidgets.py", line 1368, in _motion_notify_event
    self.set_pointer_context(x, y)
  File "/app/share/flowblade/Flowblade/tlinewidgets.py", line 1396, in set_pointer_context
    current_pointer_context = self.get_pointer_context(x, y)
  File "/app/share/flowblade/Flowblade/tlinewidgets.py", line 1409, in get_pointer_context
    hit_compositor = compositor_hit(frame, y, current_sequence().compositors)
  File "/app/share/flowblade/Flowblade/tlinewidgets.py", line 505, in compositor_hit
    track = get_track(y)
  File "/app/share/flowblade/Flowblade/tlinewidgets.py", line 450, in get_track
    audio_add = audio_add + current_sequence().tracks[i].height
IndexError: list index out of range
```

**Comment by jliljebl** [comment]
I've seen this too a few times, but it didn't hang. Haven't recreated it now, but I'm convinced that this is a real issue.

**Comment by jliljebl** [comment]
Reproduced and fixed, will be in next release.
