### ISSUE TITLE
GLib.Error: gtk-css-provider-error-quark: <broken file>:1:0Failed to import: Error opening file /usr/lib/python2.7/site-packages/Flowblade/res/css/gtk-dark-fix.css: No such file or directory (2)

### ISSUE THREAD

**Issue by martinkg** [jliljebl/flowblade#528]
Please include the following information.
1) Flowblade version (Help->About): flowblade-3fdb76d trunk
2) MLT version (Help->Runtime Environment): 6.8.0
3) Your distribution (Ubuntu, Debian, Mint etc.): Fedora 28

error message when starting recent trunk version of flowblade
```
FLOWBLADE MOVIE EDITOR 1.16
---------------------------
Launch script dir: /usr/bin
Running from installation...
modules path: /usr/lib/python2.7/site-packages/Flowblade
MLT found, version: 6.8.0
numpy version: 1.14.5
OS: Fedora 28 (Workstation Edition)
Python 2.7.15 (default, May 16 2018, 17:50:09) 
[GCC 8.1.1 20180502 (Red Hat 8.1.1-1)]
GTK+ version: 3.22.30
User dir: /home/martin/.flowblade/
Locale: None
Found translations at /usr/share/locale, using those.
Use OS locale language.
Valid shortcut files found: ['flowblade.xml', 'premiere.xml']
Keyboard shortcuts file: flowblade.xml
Loading shortcuts: Flowblade
Gtk version is 3.22.30, Flowblade theme is available.
Traceback (most recent call last):
  File "/usr/bin/flowblade", line 79, in <module>
    app.main(modules_path)
  File "/usr/lib/python2.7/site-packages/Flowblade/app.py", line 225, in main
    gui.apply_gtk_css()
  File "/usr/lib/python2.7/site-packages/Flowblade/gui.py", line 248, in apply_gtk_css
    provider.load_from_path(respaths.ROOT_PATH + "/res/css/gtk-dark-fix.css")
GLib.Error: gtk-css-provider-error-quark: <broken file>:1:0Failed to import: Error opening file /usr/lib/python2.7/site-packages/Flowblade/res/css/gtk-dark-fix.css: No such file or directory (2)
```

**Comment by jliljebl** [comment]
Ok, thanks. I'm probably going to be off the project for a couple of weeks, I'll look at this when action resumes.

**Comment by jliljebl** [comment]
This doesn't reproduce on my system, I will continue to investigate before release.

**Comment by alopatindev** [comment]
Happens to me as well

- Flowblade f000c26
- MLT 6.10.0
- Gentoo GNU/Linux

```
$ flowblade
FLOWBLADE MOVIE EDITOR 1.16
---------------------------
Launch script dir: /usr/bin
Running from installation...
modules path: /usr/share/pyshared/Flowblade
MLT found, version: 6.10.0

(flowblade:16617): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:7:34: The style property GtkButton:child-displacement-x is deprecated and shouldn't be used anymore. It will be removed in a future version

(flowblade:16617): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:8:34: The style property GtkButton:child-displacement-y is deprecated and shouldn't be used anymore. It will be removed in a future version

(flowblade:16617): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:9:28: The style property GtkButton:default-border is deprecated and shouldn't be used anymore. It will be removed in a future version

(flowblade:16617): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:10:27: The style property GtkButton:image-spacing is deprecated and shouldn't be used anymore. It will be removed in a future version

(flowblade:16617): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:11:28: The style property GtkWidget:interior-focus is deprecated and shouldn't be used anymore. It will be removed in a future version

(flowblade:16617): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:16:24: The style property GtkPaned:handle-size is deprecated and shouldn't be used anymore. It will be removed in a future version

(flowblade:16617): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:24:45: The style property GtkScrolledWindow:scrollbars-within-bevel is deprecated and shouldn't be used anymore. It will be removed in a future version

(flowblade:16617): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:32:30: The style property GtkMenu:horizontal-padding is deprecated and shouldn't be used anymore. It will be removed in a future version

(flowblade:16617): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:33:28: The style property GtkMenu:vertical-padding is deprecated and shouldn't be used anymore. It will be removed in a future version

(flowblade:16617): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:35:24: The style property GtkWidget:link-color is deprecated and shouldn't be used anymore. It will be removed in a future version

(flowblade:16617): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:36:32: The style property GtkWidget:visited-link-color is deprecated and shouldn't be used anymore. It will be removed in a future version

(flowblade:16617): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:40:29: The style property GtkWidget:wide-separators is deprecated and shouldn't be used anymore. It will be removed in a future version

(flowblade:16617): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:47:27: The style property GtkWidget:focus-padding is deprecated and shouldn't be used anymore. It will be removed in a future version

(flowblade:16617): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:48:30: The style property GtkWidget:focus-line-width is deprecated and shouldn't be used anymore. It will be removed in a future version

(flowblade:16617): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:85:13: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(flowblade:16617): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:91:12: The 'icon-shadow' property has been renamed to '-gtk-icon-shadow'

(flowblade:16617): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:168:17: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(flowblade:16617): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:188:28: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(flowblade:16617): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:291:18: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(flowblade:16617): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:583:27: The style property GtkNotebook:tab-overlap is deprecated and shouldn't be used anymore. It will be removed in a future version

(flowblade:16617): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:584:29: The style property GtkNotebook:tab-curvature is deprecated and shouldn't be used anymore. It will be removed in a future version

(flowblade:16617): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:585:27: The style property GtkNotebook:initial-gap is deprecated and shouldn't be used anymore. It will be removed in a future version

(flowblade:16617): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:597:27: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(flowblade:16617): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:665:34: The style property GtkButton:child-displacement-x is deprecated and shouldn't be used anymore. It will be removed in a future version

(flowblade:16617): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:666:34: The style property GtkButton:child-displacement-y is deprecated and shouldn't be used anymore. It will be removed in a future version

(flowblade:16617): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:674:27: The style property GtkWidget:focus-padding is deprecated and shouldn't be used anymore. It will be removed in a future version

(flowblade:16617): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:678:28: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(flowblade:16617): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:720:42: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(flowblade:16617): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:721:43: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(flowblade:16617): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:770:25: The style property GtkRange:slider-width is deprecated and shouldn't be used anymore. It will be removed in a future version

(flowblade:16617): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:771:26: The style property GtkRange:trough-border is deprecated and shouldn't be used anymore. It will be removed in a future version

(flowblade:16617): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:784:25: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(flowblade:16617): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:814:25: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(flowblade:16617): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:820:34: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(flowblade:16617): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:853:29: The style property GtkComboBox:arrow-scaling is deprecated and shouldn't be used anymore. It will be removed in a future version

(flowblade:16617): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:854:27: The style property GtkComboBox:shadow-type is deprecated and shouldn't be used anymore. It will be removed in a future version

(flowblade:16617): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:902:28: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(flowblade:16617): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:907:28: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(flowblade:16617): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:928:19: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(flowblade:16617): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:936:26: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(flowblade:16617): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:954:31: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(flowblade:16617): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:976:31: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(flowblade:16617): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:986:26: The style property GtkRange:trough-border is deprecated and shouldn't be used anymore. It will be removed in a future version

(flowblade:16617): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:987:26: The style property GtkRange:arrow-scaling is deprecated and shouldn't be used anymore. It will be removed in a future version

(flowblade:16617): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:988:25: The style property GtkRange:slider-width is deprecated and shouldn't be used anymore. It will be removed in a future version

(flowblade:16617): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:989:25: The style property GtkRange:stepper-size is deprecated and shouldn't be used anymore. It will be removed in a future version

(flowblade:16617): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:990:34: The style property GtkScrollbar:min-slider-length is deprecated and shouldn't be used anymore. It will be removed in a future version

(flowblade:16617): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:992:28: The style property GtkRange:stepper-spacing is deprecated and shouldn't be used anymore. It will be removed in a future version

(flowblade:16617): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:993:34: The style property GtkRange:trough-under-steppers is deprecated and shouldn't be used anymore. It will be removed in a future version

(flowblade:16617): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:1042:26: The :prelight pseudo-class is deprecated. Use :hover instead.

(flowblade:16617): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:1049:35: The :prelight pseudo-class is deprecated. Use :hover instead.

(flowblade:16617): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:1056:26: The :prelight pseudo-class is deprecated. Use :hover instead.

(flowblade:16617): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:1065:35: The :prelight pseudo-class is deprecated. Use :hover instead.

(flowblade:16617): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:1105:29: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(flowblade:16617): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:1106:40: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(flowblade:16617): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:1107:38: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(flowblade:16617): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:1116:29: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(flowblade:16617): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:1121:36: The :prelight pseudo-class is deprecated. Use :hover instead.

(flowblade:16617): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:1128:45: The :prelight pseudo-class is deprecated. Use :hover instead.

(flowblade:16617): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:1185:32: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(flowblade:16617): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:1211:29: The style property GtkMenuItem:arrow-scaling is deprecated and shouldn't be used anymore. It will be removed in a future version

(flowblade:16617): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:1231:24: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(flowblade:16617): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:1254:27: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(flowblade:16617): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:1255:29: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(flowblade:16617): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:1263:34: The style property GtkMenuItem:horizontal-padding is deprecated and shouldn't be used anymore. It will be removed in a future version

(flowblade:16617): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:1264:30: The style property GtkWidget:separator-height is deprecated and shouldn't be used anymore. It will be removed in a future version

(flowblade:16617): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:1317:20: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(flowblade:16617): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:1327:28: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(flowblade:16617): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:1328:36: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(flowblade:16617): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:1329:45: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(flowblade:16617): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:1330:44: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(flowblade:16617): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:1331:28: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(flowblade:16617): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:1332:36: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(flowblade:16617): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:1333:45: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(flowblade:16617): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:1334:44: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(flowblade:16617): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:1369:29: The style property GtkWidget:separator-width is deprecated and shouldn't be used anymore. It will be removed in a future version

(flowblade:16617): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:1452:12: The 'icon-shadow' property has been renamed to '-gtk-icon-shadow'

(flowblade:16617): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:1456:20: The :prelight pseudo-class is deprecated. Use :hover instead.

(flowblade:16617): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:1459:21: The :prelight pseudo-class is deprecated. Use :hover instead.

(flowblade:16617): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:1464:23: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(flowblade:16617): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:1465:24: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(flowblade:16617): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:1470:30: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(flowblade:16617): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:1471:31: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(flowblade:16617): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:1486:23: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(flowblade:16617): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:1487:23: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(flowblade:16617): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:1488:24: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(flowblade:16617): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:1489:33: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(flowblade:16617): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:1679:21: not a number

(flowblade:16617): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:1679:21: Expected a string.

(flowblade:16617): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:1696:28: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(flowblade:16617): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:1715:28: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(flowblade:16617): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:1743:20: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(flowblade:16617): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:1748:20: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(flowblade:16617): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:1810:24: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(flowblade:16617): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:1968:30: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(flowblade:16617): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:1992:42: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(flowblade:16617): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:2037:30: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(flowblade:16617): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:2170:11: not a number

(flowblade:16617): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:2170:11: Expected a string.

(flowblade:16617): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets-dark.css:13:18: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(flowblade:16617): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets-dark.css:14:31: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(flowblade:16617): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets-dark.css:15:37: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(flowblade:16617): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets-dark.css:25:25: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(flowblade:16617): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets-dark.css:26:38: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(flowblade:16617): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets-dark.css:27:44: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(flowblade:16617): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets-dark.css:32:19: The :inconsistent pseudo-class is deprecated. Use :indeterminate instead.

(flowblade:16617): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets-dark.css:33:32: The :inconsistent pseudo-class is deprecated. Use :indeterminate instead.

(flowblade:16617): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets-dark.css:34:38: The :inconsistent pseudo-class is deprecated. Use :indeterminate instead.

(flowblade:16617): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets-dark.css:38:19: The :inconsistent pseudo-class is deprecated. Use :indeterminate instead.

(flowblade:16617): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets-dark.css:38:31: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(flowblade:16617): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets-dark.css:39:32: The :inconsistent pseudo-class is deprecated. Use :indeterminate instead.

(flowblade:16617): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets-dark.css:39:44: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(flowblade:16617): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets-dark.css:40:38: The :inconsistent pseudo-class is deprecated. Use :indeterminate instead.

(flowblade:16617): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets-dark.css:40:50: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(flowblade:16617): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets-dark.css:50:18: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(flowblade:16617): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets-dark.css:51:31: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(flowblade:16617): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets-dark.css:52:37: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(flowblade:16617): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets-dark.css:62:25: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(flowblade:16617): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets-dark.css:63:38: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(flowblade:16617): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets-dark.css:64:44: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(flowblade:16617): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets-dark.css:68:19: The :inconsistent pseudo-class is deprecated. Use :indeterminate instead.

(flowblade:16617): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets-dark.css:69:32: The :inconsistent pseudo-class is deprecated. Use :indeterminate instead.

(flowblade:16617): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets-dark.css:70:38: The :inconsistent pseudo-class is deprecated. Use :indeterminate instead.

(flowblade:16617): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets-dark.css:74:19: The :inconsistent pseudo-class is deprecated. Use :indeterminate instead.

(flowblade:16617): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets-dark.css:74:31: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(flowblade:16617): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets-dark.css:75:32: The :inconsistent pseudo-class is deprecated. Use :indeterminate instead.

(flowblade:16617): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets-dark.css:75:44: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(flowblade:16617): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets-dark.css:76:38: The :inconsistent pseudo-class is deprecated. Use :indeterminate instead.

(flowblade:16617): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets-dark.css:76:50: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(flowblade:16617): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets-dark.css:82:31: The :prelight pseudo-class is deprecated. Use :hover instead.

(flowblade:16617): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets-dark.css:86:24: The :prelight pseudo-class is deprecated. Use :hover instead.

(flowblade:16617): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets-dark.css:95:33: The :prelight pseudo-class is deprecated. Use :hover instead.

(flowblade:16617): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets-dark.css:104:27: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(flowblade:16617): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets-dark.css:107:27: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(flowblade:16617): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets-dark.css:122:34: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(flowblade:16617): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets-dark.css:126:28: The :inconsistent pseudo-class is deprecated. Use :indeterminate instead.

(flowblade:16617): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets-dark.css:130:28: The :inconsistent pseudo-class is deprecated. Use :indeterminate instead.

(flowblade:16617): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets-dark.css:134:28: The :inconsistent pseudo-class is deprecated. Use :indeterminate instead.

(flowblade:16617): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets-dark.css:134:40: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(flowblade:16617): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets-dark.css:146:34: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(flowblade:16617): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets-dark.css:150:28: The :inconsistent pseudo-class is deprecated. Use :indeterminate instead.

(flowblade:16617): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets-dark.css:154:28: The :inconsistent pseudo-class is deprecated. Use :indeterminate instead.

(flowblade:16617): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets-dark.css:158:28: The :inconsistent pseudo-class is deprecated. Use :indeterminate instead.

(flowblade:16617): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets-dark.css:158:40: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(flowblade:16617): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets-dark.css:189:27: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(flowblade:16617): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets-dark.css:190:38: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(flowblade:16617): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets-dark.css:198:36: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(flowblade:16617): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets-dark.css:206:60: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(flowblade:16617): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets-dark.css:214:58: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(flowblade:16617): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets-dark.css:222:60: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(flowblade:16617): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets-dark.css:230:58: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(flowblade:16617): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets-dark.css:284:19: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(flowblade:16617): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets-dark.css:288:26: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(flowblade:16617): Gtk-WARNING **: Theme parsing error: unity.css:83:15: The 'icon-shadow' property has been renamed to '-gtk-icon-shadow'
numpy version: 1.10.4
OS: Gentoo/Linux
Python 2.7.14 (default, May  5 2018, 01:23:18)
[GCC 6.4.0]
GTK+ version: 3.22.30
User dir: /home/al/.flowblade/
prefs updated to new version, new param count: 67
Locale: en_US
Translations at /usr/share/locale were not found, using program root directory translations.
Use OS locale language.
Valid shortcut files found: ['flowblade.xml', 'premiere.xml']
Keyboard shortcuts file: flowblade.xml
Loading shortcuts: Flowblade
Gtk version is 3.22.30, Flowblade theme is available.
Traceback (most recent call last):
  File "/usr/bin/flowblade", line 80, in <module>
    app.main(modules_path)
  File "/usr/lib64/python2.7/site-packages/Flowblade/app.py", line 226, in main
    gui.apply_gtk_css()
  File "/usr/lib64/python2.7/site-packages/Flowblade/gui.py", line 249, in apply_gtk_css
    provider.load_from_path(respaths.ROOT_PATH + "/res/css/gtk-dark-fix.css")
GLib.Error: gtk-css-provider-error-quark: <broken file>:1:0Failed to import: Error opening file /usr/lib64/python2.7/site-packages/Flowblade/res/css/gtk-dark-fix.css: No such file or directory (2)
```

**Comment by jliljebl** [comment]
Still no idea on this, we all have GTK 3.22.30 and the file is in repo exactly where it is looked from by the code.

**Comment by jliljebl** [comment]
@martinkg , @alopatindev Did you install Flowblade using *setup.py*, that didn't have the css resources in it until now. I usually only remember to update *setup.py* once release starts nearing.

**Comment by alopatindev** [comment]
@jliljebl yes. Sorry that I didn't provide this detail, it was important. More precisely I used [an ebuild](https://github.com/4nykey/4nykey/blob/master/media-video/flowblade/flowblade-9999.ebuild) for Gentoo distribution.

It works now, thanks! I think we can close the issue now.

**Comment by jliljebl** [comment]
Thanks, closing.
