### ISSUE TITLE
Can't save Chinese filename.

### ISSUE THREAD

**Issue by sdnian** [jliljebl/flowblade#581]
Please include the following information.
1) Flowblade version (Help->About): 1.16.0
2) MLT version (Help->Runtime Environment): 6.10.0
3) Your distribution (Ubuntu, Debian, Mint etc.): Ubuntu 18.10
4) If possible, try to provide step-by-step instructions on how to reproduce the issue. From developer point of view this is the easieast way to understand what is happening.:

I'd like to save a project, the project name has Chinese character. I got this error:

Traceback (most recent call last):
  File "/home/steve/flowblade/flowblade-trunk/Flowblade/editorwindow.py", line 195, in <lambda>
    ('Save As', None, _('_Save As...'), None, None, lambda a:projectaction.save_project_as()),
  File "/home/steve/flowblade/flowblade-trunk/Flowblade/projectaction.py", line 445, in save_project_as
    dialogs.save_project_as_dialog(_save_as_dialog_callback, PROJECT().name, open_dir)
  File "/home/steve/flowblade/flowblade-trunk/Flowblade/dialogs.py", line 285, in save_project_as_dialog
    dialog.set_current_name(current_name)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-2: ordinal not in range(128)

This line 285 in dialogs.py should be: dialog.set_current_name(current_name.encode('utf-8')) to accept non-ascii characters as project filename.

**Comment by sdnian** [comment]
Another issue about Chinese characters..

If filename include Chinese characters and load into bin.. When load this project next time, I get below error messages..

Loading Project, SAVEFILE_VERSION: 5
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/steve/flowblade/flowblade-trunk/Flowblade/projectaction.py", line 118, in run
    project = persistance.load_project(self.filename)
  File "/home/steve/flowblade/flowblade-trunk/Flowblade/persistance.py", line 450, in load_project
    media_file.path = get_img_seq_media_path(media_file.path, _load_file_path)
  File "/home/steve/flowblade/flowblade-trunk/Flowblade/persistance.py", line 704, in get_img_seq_media_path
    path = get_img_seq_relative_path(load_file_path, path)
  File "/home/steve/flowblade/flowblade-trunk/Flowblade/persistance.py", line 732, in get_img_seq_relative_path
    _show_msg(_("Relative file search for ")  + name + "...", delay=0.0)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe6 in position 4: ordinal not in range(128)

I think the line 712 and line 732 in the persistance.py..

The original is: _show_msg(_("Relative file search for ")  + name + "...", delay=0.0)
It shoud be changed to: _show_msg(_("Relative file search for ")  + name.decode('utf-8') + "...", delay=0.0)

**Comment by sdnian** [comment]
Project -> Change Project Profile... Save new project name include Chinese characters, error message:

Saving project...
Traceback (most recent call last):
  File "/home/steve/flowblade/flowblade-trunk/Flowblade/projectaction.py", line 544, in _change_project_profile_callback
    persistance.save_project(PROJECT(), path, profile.description()) #<----- HERE
  File "/home/steve/flowblade/flowblade-trunk/Flowblade/persistance.py", line 197, in save_project
    with atomicfile.AtomicFileWriter(file_path, "wb") as afw:
  File "/home/steve/flowblade/flowblade-trunk/Flowblade/atomicfile.py", line 104, in __enter__
    fd = os.open(maybe_tmp_file_path, os.O_WRONLY|os.O_CREAT|os.O_EXCL, 0o666)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 38-40: ordinal not in range(128)

Change the line 538 in projectaction.py:

original: path = folder + u"/" + name
fix the error: path = (folder + u"/" + name).encode('utf-8')

**Comment by sdnian** [comment]
File -> Export -> MLT XML, error message:

Traceback (most recent call last):
  File "/home/steve/flowblade/flowblade-trunk/Flowblade/editorwindow.py", line 198, in <lambda>
    ('ExportMeltXML', None, _('MLT XML'), None, None, lambda a:exporting.MELT_XML_export()),
  File "/home/steve/flowblade/flowblade-trunk/Flowblade/exporting.py", line 55, in MELT_XML_export
    dialogs.export_xml_dialog(_export_melt_xml_dialog_callback, PROJECT().name)
  File "/home/steve/flowblade/flowblade-trunk/Flowblade/dialogs.py", line 343, in export_xml_dialog
    _export_file_name_dialog(callback, project_name, _("Export Project as XML to"))
  File "/home/steve/flowblade/flowblade-trunk/Flowblade/dialogs.py", line 352, in _export_file_name_dialog
    dialog.set_current_name(project_name + u".xml")
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-2: ordinal not in range(128)

Line 352 in dialogs.py:

original: dialog.set_current_name(project_name + ".xml")
fix it: dialog.set_current_name(project_name.encode('utf-8') + ".xml")

**Comment by sdnian** [comment]
File -> Export -> EDL, error message:

Traceback (most recent call last):
  File "/home/steve/flowblade/flowblade-trunk/Flowblade/editorwindow.py", line 199, in <lambda>
    ('ExportEDL', None, _('EDL'), None, None, lambda a:exporting.EDL_export()),
  File "/home/steve/flowblade/flowblade-trunk/Flowblade/exporting.py", line 79, in EDL_export
    dialogs.export_edl_dialog(_export_edl_dialog_callback, gui.editor_window.window, PROJECT().name)
  File "/home/steve/flowblade/flowblade-trunk/Flowblade/dialogs.py", line 1266, in export_edl_dialog
    dialog.set_current_name(project_name + ".edl")
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-2: ordinal not in range(128)

Line 1266 in dialogs.py:

original: dialog.set_current_name(project_name + ".edl")
fix it: dialog.set_current_name(project_name.encode('utf-8') + ".edl")

Line 100 in exporting.py:

original: f.write(edl_contents)
fix it: f.write(edl_contents.encode('utf-8'))

**Comment by jliljebl** [comment]
Alright, for some reason these *worked* here without the *.encode('utf-8')* thing. I tried with your  translation's Chinese characters, and it all worked. Maybe you have your OS running on zh_TW and that causes the difference. 

However, I will patch according to your suggestions because everything still seems to be working here after the patches and they will probably fix your Issues.

I'm disappointed that we are getting differing behavior here, this is not a good state of affairs and Python platform should do better.

**Comment by jliljebl** [comment]
I pushed patches for these, if there are more comment here and I'll push patches.

**Comment by jliljebl** [comment]
I did one more patch to fix this. I'm closing as *fixed* but if we find more of these we will obviously reopen.
