### ISSUE TITLE
traceback when clicking Menu entry edit/Disk Cache Manager

### ISSUE THREAD

**Issue by empee0** [jliljebl/flowblade#685]
Hi,
on master (a54aef8) I have the following issue when clicking on menu entry disk cache manager:

Traceback (most recent call last):
  File "/home/mpeter/install/flowblade/flowblade-trunk/Flowblade/editorwindow.py", line 229, in <lambda>
    ('DiskCacheManager', None, _('Disk Cache Manager'), None, None, lambda a:diskcachemanagement.show_disk_management_dialog()),
  File "/home/mpeter/install/flowblade/flowblade-trunk/Flowblade/diskcachemanagement.py", line 153, in show_disk_management_dialog
    _panels = _get_disk_dir_panels()
  File "/home/mpeter/install/flowblade/flowblade-trunk/Flowblade/diskcachemanagement.py", line 176, in _get_disk_dir_panels
    panels.append(DiskFolderManagementPanel(appconsts.USER_PROFILES_DIR_NO_SLASH, _("User Created Custom Profiles"), PROJECT_DATA_WARNING))
  File "/home/mpeter/install/flowblade/flowblade-trunk/Flowblade/diskcachemanagement.py", line 53, in __init__
    self.size_info.set_text(self.get_folder_size_str())
  File "/home/mpeter/install/flowblade/flowblade-trunk/Flowblade/diskcachemanagement.py", line 99, in get_folder_size_str
    size = self.get_folder_size()
  File "/home/mpeter/install/flowblade/flowblade-trunk/Flowblade/diskcachemanagement.py", line 92, in get_folder_size
    files = self.get_folder_files()
  File "/home/mpeter/install/flowblade/flowblade-trunk/Flowblade/diskcachemanagement.py", line 89, in get_folder_files
    return [f for f in listdir(cache_folder) if isfile(join(cache_folder, f))]
OSError: [Errno 2] No such file or directory: '/home/mpeter/.cache/flowblade/user_profiles'

are you aware about this?
regards Mario

**Comment by jliljebl** [comment]
Yeah, i just remembered that there was some issue with feature got the same on test. Needs obivously fixing before release, might take a few days, still doing some other related things.

**Comment by jliljebl** [comment]
Ok, fixed this.
