### ISSUE TITLE
Can't startup Flowblade due to module 'MLT' not being found on Manjaro system

### ISSUE THREAD

**Issue by Noah11012** [jliljebl/flowblade#693]
Output:

```
flowblade/flowblade-trunk on  master
➜ python2.7 ./flowblade
FLOWBLADE MOVIE EDITOR 2.2
--------------------------
Launch script dir: /home/noah/Desktop/Documents/flowblade/flowblade-trunk
Running from filesystem...
MLT found but version info not available. MLT probably too old to work reliably...
/home/noah/Desktop/Documents/flowblade/flowblade-trunk/Flowblade/clipeffectseditor.py:483: SyntaxWarning: name 'current_filter_index' is used prior to global declaration
  global current_filter_index
/home/noah/Desktop/Documents/flowblade/flowblade-trunk/Flowblade/propertyeditorbuilder.py:193: SyntaxWarning: name 'changing_slider_to_kf_property_name' is used prior to global declaration
  global changing_slider_to_kf_property_name
/home/noah/Desktop/Documents/flowblade/flowblade-trunk/Flowblade/tlinewidgets.py:370: SyntaxWarning: name 'TRACK_GRAD_ORANGE_STOP1' is assigned to before global declaration
  global TRACK_GRAD_ORANGE_STOP1,TRACK_GRAD_ORANGE_STOP3,TRACK_GRAD_STOP1,TRACK_GRAD_STOP3
/home/noah/Desktop/Documents/flowblade/flowblade-trunk/Flowblade/tlinewidgets.py:370: SyntaxWarning: name 'TRACK_GRAD_ORANGE_STOP3' is assigned to before global declaration
  global TRACK_GRAD_ORANGE_STOP1,TRACK_GRAD_ORANGE_STOP3,TRACK_GRAD_STOP1,TRACK_GRAD_STOP3
/home/noah/Desktop/Documents/flowblade/flowblade-trunk/Flowblade/tlinewidgets.py:370: SyntaxWarning: name 'TRACK_GRAD_STOP1' is assigned to before global declaration
  global TRACK_GRAD_ORANGE_STOP1,TRACK_GRAD_ORANGE_STOP3,TRACK_GRAD_STOP1,TRACK_GRAD_STOP3
/home/noah/Desktop/Documents/flowblade/flowblade-trunk/Flowblade/tlinewidgets.py:370: SyntaxWarning: name 'TRACK_GRAD_STOP3' is assigned to before global declaration
  global TRACK_GRAD_ORANGE_STOP1,TRACK_GRAD_ORANGE_STOP3,TRACK_GRAD_STOP1,TRACK_GRAD_STOP3
/home/noah/Desktop/Documents/flowblade/flowblade-trunk/Flowblade/projectaction.py:774: SyntaxWarning: name 'force_overwrite' is used prior to global declaration
  global force_overwrite, force_proxy
/home/noah/Desktop/Documents/flowblade/flowblade-trunk/Flowblade/projectaction.py:774: SyntaxWarning: name 'force_proxy' is used prior to global declaration
  global force_overwrite, force_proxy
numpy version: 1.16.4
Application version: 2.2.0
OS: Manjaro Linux
Python 2.7.16 (default, Mar 11 2019, 18:59:25)
[GCC 8.2.1 20181127]
GTK+ version: 3.24.10
XDG user data exists.
Locale: en_US
Found translations at /home/noah/Desktop/Documents/flowblade/flowblade-trunk/Flowblade/locale/, using those.
Use OS locale language.
Valid shortcut files found: ['flowblade.xml', 'premiere.xml']
Keyboard shortcuts file: flowblade.xml
Loading shortcuts: Flowblade
Initializing Auto Save Options
Gtk version is 3.24.10, Flowblade theme is available.
Screen size: 1600 x 900
Small height: True
Small width: False
Traceback (most recent call last):
  File "./flowblade", line 91, in <module>
    app.main(modules_path)
  File "/home/noah/Desktop/Documents/flowblade/flowblade-trunk/Flowblade/app.py", line 246, in main
    repo = mlt.Factory().init()
AttributeError: 'module' object has no attribute 'Factory'

flowblade/flowblade-trunk on  master
➜
```

**Comment by dvdlvr** [comment]
Hi,

This bit of the provided output gives more info:
"MLT found but version info not available. MLT probably too old to work reliably..."

You also do not specify the MLT version in your bug report, so I would start with installing a more recent version of MLT and try again.

**Comment by Noah11012** [comment]
Sorry, about that. I couldn't get the MLT version because I couldn't startup Flowblade and view the version there.

MLT version I got by running melt --version:
6.16.0

**Comment by jliljebl** [comment]
I can't believe the Issue is with Flowblade code here, the MLT installation on your system is somehow not functioning as it is supposed to, mlt module should absolutely have attribute Factory.

**Comment by Noah11012** [comment]
Fixed it here: https://forum.manjaro.org/t/solved-flowblade-2-0-error-no-module-named-mlt/84636/5

**Comment by jliljebl** [comment]
Ok, good, I'll keep this open for info until next release.

**Comment by timbze** [comment]
I had this same issue because I had followed some instructions to do "pip install mlt" while trying to use Flowblade from source. I had to do "pip uninstall mlt" and I'm set.

**Comment by jliljebl** [comment]
This should now be resolved.
