### ISSUE TITLE
UnicodeDecodeError in Manjaro with release 2.4

### ISSUE THREAD

**Issue by oberon-manjaro** [jliljebl/flowblade#798]
On **Manjarolinux** (**mlt 6.18.0**)
Launching **flowblade 2.4** fails with:

```
Traceback (most recent call last):
  File "/usr/bin/flowblade", line 93, in <module>
    app.main(modules_path)
  File "/usr/share/pyshared/Flowblade/app.py", line 170, in main
    editorpersistance.load()
  File "/usr/share/pyshared/Flowblade/editorpersistance.py", line 73, in load
    with atomicfile.AtomicFileWriter(prefs_file_path, "wb") as afw:
  File "/usr/share/pyshared/Flowblade/atomicfile.py", line 114, in __enter__
    maybe_tmp_filename = self.__get_random_filename(self.basename)
  File "/usr/share/pyshared/Flowblade/atomicfile.py", line 225, in __get_random_filename
    uuid_str = hashlib.md5(str(os.urandom(32)).encode('utf-8')).hexdigest()
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf1 in position 1: ordinal not in range(128)
```
release 2.2 is still working fine on Manjaro.

**Comment by jliljebl** [comment]
Flowblade 2.4 is Python 3 application, this seems you are running Flowblade 2.4 on Python 2?

**Comment by oberon-manjaro** [comment]
I have already changed the dependencies and built against python 3:
```
depends=('dbus-glib'
         'frei0r-plugins'
         'gmic'
         'gtk3'
         'librsvg'
         'mlt'
         'mlt-python2-bindings'
         'movit'
         'pygtk'
         'python-dbus'
         'python-gobject'
         'python-numpy'
         'python-pillow'
         'sdl_image'
         'sox'
         'swh-plugins')
```

**Comment by oberon-manjaro** [comment]
Ok. now I see that I missed mlt-python-bindings :stuck_out_tongue_winking_eye:

**Comment by oberon-manjaro** [comment]
Unfortunately, with adjusted dependencies i still see the same error:

```
depends=('dbus-glib'
         'frei0r-plugins'
         'gmic'
         'gtk3'
         'librsvg'
         'mlt'
         'movit'
         'pygtk'
         'python-dbus'
         'python-gobject'
         'python-mlt'
         'python-numpy'
         'python-pillow'
         'sdl_image'
         'sox'
         'swh-plugins')
```

**Comment by oberon-manjaro** [comment]
I guess the problem might be pygtk, which is still exclusivel gtk2 afaik ...

**Comment by jliljebl** [comment]
Yeah, we should have every 2.4 everywhere crashing with this if this was an application code problem. This really is some py2/py3 issue, can't think offhand any suggestions on fixing this.

**Comment by oberon-manjaro** [comment]
A rebuild with **pygobject-devel** still fails ...

**Comment by oberon-manjaro** [comment]
On the error message I found this:
https://stackoverflow.com/questions/21129020/how-to-fix-unicodedecodeerror-ascii-codec-cant-decode-byte

**Comment by jliljebl** [comment]
Whne you start applcation it print the Python version, are sure it says 3.x


FLOWBLADE MOVIE EDITOR 2.4
--------------------------
Launch script dir: /home/janne/codes/flowblade/flowblade/flowblade-trunk
Running from filesystem...
MLT found, version: 6.17.0
numpy version: 1.16.2
Application version: 2.4.0
OS: Ubuntu 19.10
Python 3.7.5 (default, Nov 20 2019, 09:21:52)   **<- HERE**
[GCC 9.2.1 20191008]
GTK+ version: 3.24.12

**Comment by oberon-manjaro** [comment]
Thank you for your help. I found the problem. There was still a python2 command in my build, my bad! Now everything works.

**Comment by jliljebl** [comment]
Alright, great.

**Comment by oberon-manjaro** [comment]
```
$ flowblade
FLOWBLADE MOVIE EDITOR 2.4
--------------------------
Launch script dir: /usr/bin
Running from installation...
modules path: /usr/share/pyshared/Flowblade
MLT found, version: 6.18.0

(flowblade:29187): Gtk-WARNING **: 14:53:10.726: Theme parsing error: gtk.css:68:35: The style property GtkButton:child-displacement-x is deprecated and shouldn't be used anymore. It will be removed in a future version

(flowblade:29187): Gtk-WARNING **: 14:53:10.726: Theme parsing error: gtk.css:69:35: The style property GtkButton:child-displacement-y is deprecated and shouldn't be used anymore. It will be removed in a future version

(flowblade:29187): Gtk-WARNING **: 14:53:10.726: Theme parsing error: gtk.css:73:46: The style property GtkScrolledWindow:scrollbars-within-bevel is deprecated and shouldn't be used anymore. It will be removed in a future version
numpy version: 1.18.1
Application version: 2.4.0
OS: Manjaro Linux
Python 3.8.1 (default, Dec 21 2019, 20:57:38) 
[GCC 9.2.0]
GTK+ version: 3.24.13
XDG user data exists.
prefs updated to new version, new param count: 77
Locale: en_GB
Translations at /usr/share/locale were not found, using program root directory translations.
Use OS locale language.
Valid shortcut files found: ['flowblade.xml', 'premiere.xml']
Keyboard shortcuts file: flowblade.xml
Loading shortcuts: Flowblade
Initializing Auto Save Options
Gtk version is 3.24.13, Flowblade theme is available.

(flowblade:29187): Gtk-WARNING **: 14:53:10.960: Theme parsing error: gtk.css:68:35: The style property GtkButton:child-displacement-x is deprecated and shouldn't be used anymore. It will be removed in a future version

(flowblade:29187): Gtk-WARNING **: 14:53:10.960: Theme parsing error: gtk.css:69:35: The style property GtkButton:child-displacement-y is deprecated and shouldn't be used anymore. It will be removed in a future version

(flowblade:29187): Gtk-WARNING **: 14:53:10.960: Theme parsing error: gtk.css:71:36: The style property GtkCheckMenuItem:indicator-size is deprecated and shouldn't be used anymore. It will be removed in a future version

(flowblade:29187): Gtk-WARNING **: 14:53:10.960: Theme parsing error: gtk.css:73:46: The style property GtkScrolledWindow:scrollbars-within-bevel is deprecated and shouldn't be used anymore. It will be removed in a future version

(flowblade:29187): Gtk-WARNING **: 14:53:10.960: Theme parsing error: gtk.css:76:30: The style property GtkExpander:expander-size is deprecated and shouldn't be used anymore. It will be removed in a future version
Using Full Screen size for layout: 1920 x 1080
Small height: False
Small width: False
Detecting environment...
```
