### ISSUE TITLE
object has no attribute tline_render_mode

### ISSUE THREAD

**Issue by duanev** [jliljebl/flowblade#853]
with a checkout from github 2020/04/25 (2.4, MLT 6.20.0, GTK 3.24.17, Arch)
When I load a previous .flb I get:
```
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/duanev/git/flowblade/flowblade-trunk/Flowblade/projectaction.py", line 178, in run
    app.open_project(project)
  File "/home/duanev/git/flowblade/flowblade-trunk/Flowblade/app.py", line 645, in open_project
    init_sequence_gui()
  File "/home/duanev/git/flowblade/flowblade-trunk/Flowblade/app.py", line 563, in init_sequence_gui
    gui.editor_window.init_timeline_rendering_menu()
  File "/home/duanev/git/flowblade/flowblade-trunk/Flowblade/editorwindow.py", line 1143, in init_timeline_rendering_menu
    menu_items[editorstate.get_tline_rendering_mode()].set_active(True)
  File "/home/duanev/git/flowblade/flowblade-trunk/Flowblade/editorstate.py", line 200, in get_tline_rendering_mode
    return project.c_seq.tline_render_mode
AttributeError: 'Sequence' object has no attribute 'tline_render_mode'
```
which I hacked a workaround for (starting at #195 in Flowblade/editorstate.py):
```
def get_tline_rendering_mode():
    if project.c_seq == None:
        print ("get_compositing_mode(), trying to get timeline render mode when no current sequence available!") 
        return appconsts.TLINE_RENDERING_OFF
    else:
        try:
            rc = project.c_seq.tline_render_mode
        except AttributeError:
            rc = appconsts.TLINE_RENDERING_OFF
        return rc
```

**Comment by jliljebl** [comment]
Ok, current code does not work with older projects. Timeline rendering is new feature that has not yet been finalized and release tested for next release, so there might still be issues. 

Thanks for the head up, this will be tested and fixed before release.

**Comment by jliljebl** [comment]
I made timeline render mode tobe  a editor state property which fixes this too.
