### ISSUE TITLE
Не работает "Edit Container Program"

### ISSUE THREAD

**Issue by smolnp** [jliljebl/flowblade#881]
MLT found, version: 6.20.0
numpy version: 1.18.4
Application version: 2.6.0
OS: Fedora 32 (Cinnamon)
Python 3.8.3 (default, May 29 2020, 00:00:00) 
[GCC 10.1.1 20200507 (Red Hat 10.1.1-1)]
GTK+ version: 3.24.20
XDG user data exists.
Locale: ru_RU

When "Edit Container Program" is selected, nothing happens

Terminal output:
Traceback (most recent call last):
  File "/home/semya/flowblade-master/flowblade-trunk/Flowblade/clipmenuaction.py", line 99, in _clip_menu_item_activated
    handler(data)
  File "/home/semya/flowblade-master/flowblade-trunk/Flowblade/containerclip.py", line 135, in edit_program
    action_object.edit_program(clip)
  File "/home/semya/flowblade-master/flowblade-trunk/Flowblade/containeractions.py", line 848, in edit_program
    simpleeditors.show_blender_container_clip_program_editor(self.project_edit_done, clip, self, self.container_data.data_slots["project_edit_info"])
  File "/home/semya/flowblade-master/flowblade-trunk/Flowblade/tools/simpleeditors.py", line 61, in show_blender_container_clip_program_editor
    editor_window = BlenderProgramEditorWindow(callback, clip, container_action, program_info_json)
  File "/home/semya/flowblade-master/flowblade-trunk/Flowblade/tools/simpleeditors.py", line 103, in __init__
    elif editorstate.screen_size_small_height() == True and editorste.screen_size_large_height() == False and n_editors > 5:
NameError: name 'editorste' is not defined

**Comment by jliljebl** [comment]
Confirmed and fixed, thanks. I'll wait 2 weeks to see if we get more these and then do a point release to fix bugs.
