### ISSUE TITLE
flatpak 2.6.1 hangs on opening saves

### ISSUE THREAD

**Issue by Mq89** [jliljebl/flowblade#919]
When I start flowblade and load saved *.flb file it hangs at "Loading icons...".
I'm using Lubuntu 16.04.
I installed flowblade via flatpak. I don't have python 3.8 installed.
Running in console produces the following output:

```
12:40:56 markus@aldricon ~/[REDACTED] $ flatpak run io.github.jliljebl.Flowblade
FLOWBLADE MOVIE EDITOR 2.6.1
----------------------------
Launch script dir: /app/bin
Running from Flatpak installation...
modules path: /app/share/flowblade/Flowblade
MLT found, version: 6.18.0
numpy version: 1.17.4
Application version: 2.6.1
OS: GNOME 3.38 (Flatpak runtime)
Python 3.8.5 (default, Nov 10 2011, 15:00:00) 
[GCC 10.2.0]
GTK+ version: 3.24.23
XDG user data exists.
Locale: de_DE
Found translations at /app/share/flowblade/Flowblade/locale, using those.
Force use English.
Valid shortcut files found: ['flowblade.xml', 'premiere.xml']
Keyboard shortcuts file: flowblade.xml
Loading shortcuts: Flowblade
Gtk version is 3.24.23, Flowblade theme is available.
Using Full Screen size for layout: 3120 x 2504
Small height: False
Small width: False
Detecting environment...
---
video_codecs:
  - a64multi
  - a64multi5
  - alias_pix
  - amv
  - apng
  - asv1
  - asv2
  - avrp
  - avui
  - ayuv
  - bmp
  - cinepak
  - cljr
  - dnxhd
  - dpx
  - dvvideo
  - ffv1
  - ffvhuff
  - fits
  - flashsv
  - flashsv2
  - flv
  - gif
  - h261
  - h263
  - h263p
  - huffyuv
  - jpeg2000
  - jpegls
  - ljpeg
  - magicyuv
  - mjpeg
  - mpeg1video
  - mpeg2video
  - mpeg4
  - msmpeg4v2
  - msmpeg4
  - msvideo1
  - pam
  - pbm
  - pcx
  - pgm
  - pgmyuv
  - png
  - ppm
  - prores
  - prores_aw
  - prores_ks
  - qtrle
  - r10k
  - r210
  - rawvideo
  - roqvideo
  - rv10
  - rv20
  - sgi
  - snow
  - sunrast
  - svq1
  - targa
  - tiff
  - utvideo
  - v210
  - v308
  - v408
  - v410
  - vc2
  - wrapped_avframe
  - wmv1
  - wmv2
  - xbm
  - xface
  - xwd
  - y41p
  - yuv4
  - zlib
  - zmbv
  - libvpx
  - libvpx-vp9
  - libx264
  - libx264rgb
  - h263_v4l2m2m
  - h264_v4l2m2m
  - h264_vaapi
  - hevc_v4l2m2m
  - hevc_vaapi
  - mjpeg_vaapi
  - mpeg2_vaapi
  - mpeg4_v4l2m2m
  - vp8_v4l2m2m
  - vp8_vaapi
  - vp9_vaapi
...
---
audio_codecs:
  - comfortnoise
  - s302m
  - aac
  - ac3
  - ac3_fixed
  - alac
  - aptx
  - aptx_hd
  - dca
  - eac3
  - flac
  - g723_1
  - mlp
  - mp2
  - mp2fixed
  - nellymoser
  - opus
  - real_144
  - sbc
  - sonic
  - sonicls
  - truehd
  - tta
  - vorbis
  - wavpack
  - wmav1
  - wmav2
  - pcm_alaw
  - pcm_dvd
  - pcm_f32be
  - pcm_f32le
  - pcm_f64be
  - pcm_f64le
  - pcm_mulaw
  - pcm_s8
  - pcm_s8_planar
  - pcm_s16be
  - pcm_s16be_planar
  - pcm_s16le
  - pcm_s16le_planar
  - pcm_s24be
  - pcm_s24daud
  - pcm_s24le
  - pcm_s24le_planar
  - pcm_s32be
  - pcm_s32le
  - pcm_s32le_planar
  - pcm_s64be
  - pcm_s64le
  - pcm_u8
  - pcm_u16be
  - pcm_u16le
  - pcm_u24be
  - pcm_u24le
  - pcm_u32be
  - pcm_u32le
  - pcm_vidc
  - roq_dpcm
  - adpcm_adx
  - g722
  - g726
  - g726le
  - adpcm_ima_qt
  - adpcm_ima_wav
  - adpcm_ms
  - adpcm_swf
  - adpcm_yamaha
  - libmp3lame
  - libopus
...
---
formats:
  - a64
  - ac3
  - adts
  - adx
  - aiff
  - amr
  - apng
  - aptx
  - aptx_hd
  - asf
  - ass
  - ast
  - asf_stream
  - au
  - avi
  - avm2
  - avs2
  - bit
  - caf
  - cavsvideo
  - codec2
  - codec2raw
  - crc
  - dash
  - data
  - daud
  - dirac
  - dnxhd
  - dts
  - dv
  - eac3
  - f4v
  - ffmetadata
  - fifo
  - fifo_test
  - filmstrip
  - fits
  - flac
  - flv
  - framecrc
  - framehash
  - framemd5
  - g722
  - g723_1
  - g726
  - g726le
  - gif
  - gsm
  - gxf
  - h261
  - h263
  - h264
  - hash
  - hds
  - hevc
  - hls
  - ico
  - ilbc
  - image2
  - image2pipe
  - ipod
  - ircam
  - ismv
  - ivf
  - jacosub
  - latm
  - lrc
  - m4v
  - md5
  - matroska
  - matroska
  - microdvd
  - mjpeg
  - mlp
  - mmf
  - mov
  - mp2
  - mp3
  - mp4
  - mpeg
  - vcd
  - mpeg1video
  - dvd
  - svcd
  - mpeg2video
  - vob
  - mpegts
  - mpjpeg
  - mxf
  - mxf_d10
  - mxf_opatom
  - null
  - nut
  - oga
  - ogg
  - ogv
  - oma
  - opus
  - alaw
  - mulaw
  - vidc
  - f64be
  - f64le
  - f32be
  - f32le
  - s32be
  - s32le
  - s24be
  - s24le
  - s16be
  - s16le
  - s8
  - u32be
  - u32le
  - u24be
  - u24le
  - u16be
  - u16le
  - u8
  - psp
  - rawvideo
  - rm
  - roq
  - rso
  - rtp
  - rtp_mpegts
  - rtsp
  - sap
  - sbc
  - scc
  - film_cpk
  - segment
  - stream_segment,ssegment
  - singlejpeg
  - smjpeg
  - smoothstreaming
  - sox
  - spx
  - spdif
  - srt
  - sup
  - swf
  - tee
  - 3g2
  - 3gp
  - mkvtimestamp_v2
  - truehd
  - tta
  - uncodedframecrc
  - vc1
  - vc1test
  - voc
  - w64
  - wav
  - webm
  - webm_dash_manifest
  - webm_chunk
  - webp
  - webvtt
  - wtv
  - wv
  - yuv4mpegpipe
  - alsa
  - fbdev
  - oss
  - sdl,sdl2
  - video4linux2,v4l2
  - xv
...
MLT detection succeeded, 168 formats, 92 video codecs and 69 audio codecs found.
565 MLT services found.
Loading render profiles...
Loading filters...
Brightness dropped, MLT version too high for this filter.
Brightness Keyframed dropped, MLT version too high for this filter.
Loading transitions...
RGB Adjustment dropped for Color Adjustment
Hue dropped for Color Adjustment
Gamma dropped for Lift Gain Gamma
G'MIC found
Player initialized with profile:  HD 1080p 30 fps
Selected color NOT detected
BG color detected
Create SDL1 consumer...
Launching io.github.jliljebl.Flowblade dbus service
Autosave started...
Saving project...
No user folders actions needed.
Loading Project, SAVEFILE_VERSION: 5
window resized FAILED
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7f7dd0079b00] st: 0 edit list: 1 Missing key frame while searching for timestamp: 1000
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7f7dd0079b00] st: 0 edit list 1 Cannot find an index entry before timestamp: 1000.
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7f7dd007dcc0] st: 0 edit list: 1 Missing key frame while searching for timestamp: 1000
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7f7dd007dcc0] st: 0 edit list 1 Cannot find an index entry before timestamp: 1000.
[ogg @ 0x7f7dd009b380] Broken file, keyframe not correctly marked.
[ogg @ 0x7f7dd009b380] Broken file, keyframe not correctly marked.
[ogg @ 0x7f7dd033a680] Broken file, keyframe not correctly marked.
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7f7dd07a0b40] st: 0 edit list: 1 Missing key frame while searching for timestamp: 1000
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7f7dd07a0b40] st: 0 edit list 1 Cannot find an index entry before timestamp: 1000.
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7f7dd0839e40] st: 0 edit list: 1 Missing key frame while searching for timestamp: 1000
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7f7dd0839e40] st: 0 edit list 1 Cannot find an index entry before timestamp: 1000.
[ogg @ 0x7f7dd07d9d00] Broken file, keyframe not correctly marked.
[ogg @ 0x7f7dd07d9d00] Broken file, keyframe not correctly marked.
[ogg @ 0x7f7dd082d300] Broken file, keyframe not correctly marked.
[ogg @ 0x7f7dd07deb00] Broken file, keyframe not correctly marked.
[ogg @ 0x7f7dd07deb00] Broken file, keyframe not correctly marked.
[ogg @ 0x7f7dd07df740] Broken file, keyframe not correctly marked.
[ogg @ 0x7f7dd080b480] Broken file, keyframe not correctly marked.
[ogg @ 0x7f7dd080b480] Broken file, keyframe not correctly marked.
[ogg @ 0x7f7dd0604080] Broken file, keyframe not correctly marked.
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7f7dd05b1340] st: 0 edit list: 1 Missing key frame while searching for timestamp: 1000
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7f7dd05b1340] st: 0 edit list 1 Cannot find an index entry before timestamp: 1000.
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7f7dd05b9440] st: 0 edit list: 1 Missing key frame while searching for timestamp: 1000
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7f7dd05b9440] st: 0 edit list 1 Cannot find an index entry before timestamp: 1000.
[ogg @ 0x7f7dd02b95c0] Broken file, keyframe not correctly marked.
[ogg @ 0x7f7dd02b95c0] Broken file, keyframe not correctly marked.
[ogg @ 0x7f7dd02a8500] Broken file, keyframe not correctly marked.
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7f7dd1264380] st: 0 edit list: 1 Missing key frame while searching for timestamp: 1000
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7f7dd1264380] st: 0 edit list 1 Cannot find an index entry before timestamp: 1000.
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7f7dd1f38d40] st: 0 edit list: 1 Missing key frame while searching for timestamp: 1000
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7f7dd1f38d40] st: 0 edit list 1 Cannot find an index entry before timestamp: 1000.
[ogg @ 0x7f7dd12f4c80] Broken file, keyframe not correctly marked.
[ogg @ 0x7f7dd12f4c80] Broken file, keyframe not correctly marked.
[ogg @ 0x7f7dd1fdea00] Broken file, keyframe not correctly marked.
[ogg @ 0x7f7dd12ca940] Broken file, keyframe not correctly marked.
[ogg @ 0x7f7dd12ca940] Broken file, keyframe not correctly marked.
[ogg @ 0x7f7dd301c740] Broken file, keyframe not correctly marked.
[ogg @ 0x7f7dd2edd0c0] Broken file, keyframe not correctly marked.
[ogg @ 0x7f7dd2edd0c0] Broken file, keyframe not correctly marked.
[ogg @ 0x7f7dd2edf9c0] Broken file, keyframe not correctly marked.
[ogg @ 0x7f7dd2ed1dc0] Broken file, keyframe not correctly marked.
[ogg @ 0x7f7dd2ed1dc0] Broken file, keyframe not correctly marked.
[ogg @ 0x7f7dd2ed4dc0] Broken file, keyframe not correctly marked.
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7f7dd24c74c0] st: 0 edit list: 1 Missing key frame while searching for timestamp: 1000
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7f7dd24c74c0] st: 0 edit list 1 Cannot find an index entry before timestamp: 1000.
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7f7dd24cad40] st: 0 edit list: 1 Missing key frame while searching for timestamp: 1000
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7f7dd24cad40] st: 0 edit list 1 Cannot find an index entry before timestamp: 1000.
[ogg @ 0x7f7dd3376680] Broken file, keyframe not correctly marked.
[ogg @ 0x7f7dd3376680] Broken file, keyframe not correctly marked.
[ogg @ 0x7f7dd33d4200] Broken file, keyframe not correctly marked.
[ogg @ 0x7f7dd3fe3a00] Broken file, keyframe not correctly marked.
[ogg @ 0x7f7dd3fe3a00] Broken file, keyframe not correctly marked.
[ogg @ 0x7f7dd24f2ec0] Broken file, keyframe not correctly marked.
[ogg @ 0x7f7d781c5940] Broken file, keyframe not correctly marked.
[ogg @ 0x7f7d781c5940] Broken file, keyframe not correctly marked.
[ogg @ 0x7f7d781c6f40] Broken file, keyframe not correctly marked.
[ogg @ 0x7f7dd2d2c880] Broken file, keyframe not correctly marked.
[ogg @ 0x7f7dd2d2c880] Broken file, keyframe not correctly marked.
[ogg @ 0x7f7d78084680] Broken file, keyframe not correctly marked.
[producer_xml] failed to load producer "[REDACTED]"
[producer_xml] failed to load producer "[REDACTED]"
[producer_xml] failed to load producer "[REDACTED]"
[producer_xml] failed to load producer "[REDACTED]"
[producer_xml] failed to load producer "[REDACTED]"
[producer_xml] failed to load producer "[REDACTED]"
[producer_xml] failed to load producer "[REDACTED]"
[producer_xml] failed to load producer "[REDACTED]"
[producer_xml] failed to load producer "[REDACTED]"
[producer_xml] failed to load producer "[REDACTED]"
[producer_xml] failed to load producer "[REDACTED]"
[producer_xml] failed to load producer "[REDACTED]"
[producer_xml] failed to load producer "[REDACTED]"
[producer_xml] failed to load producer "[REDACTED]"
[producer_xml] failed to load producer "[REDACTED]"
[producer_xml] failed to load producer "[REDACTED]"
[producer_xml] failed to load producer "[REDACTED]"
[producer_xml] failed to load producer "[REDACTED]"
[producer_xml] failed to load producer "[REDACTED]"
[producer_xml] failed to load producer "[REDACTED]"
[producer_xml] failed to load producer "[REDACTED]"
[producer_xml] failed to load producer "[REDACTED]"
[producer_xml] failed to load producer "[REDACTED]"
[producer_xml] failed to load producer "[REDACTED]"
[producer_xml] failed to load producer "[REDACTED]"
[producer_xml] failed to load producer "[REDACTED]"
[producer_xml] failed to load producer "[REDACTED]"
[producer_xml] failed to load producer "[REDACTED]"
[producer_xml] failed to load producer "[REDACTED]"
[producer_xml] failed to load producer "[REDACTED]"
[producer_xml] failed to load producer "[REDACTED]"
[producer_xml] failed to load producer "[REDACTED]"
[producer_xml] failed to load producer "[REDACTED]"
[producer_xml] failed to load producer "[REDACTED]"
failed to make icon from: /usr/lib/python3.8/site-packages/Flowblade/res/darktheme/fallback_thumb.png
failed to make icon from: /usr/lib/python3.8/site-packages/Flowblade/res/darktheme/fallback_thumb.png
failed to make icon from: /usr/lib/python3.8/site-packages/Flowblade/res/darktheme/fallback_thumb.png
failed to make icon from: /usr/lib/python3.8/site-packages/Flowblade/res/darktheme/fallback_thumb.png
failed to make icon from: /usr/lib/python3.8/site-packages/Flowblade/res/darktheme/fallback_thumb.png
failed to make icon from: /usr/lib/python3.8/site-packages/Flowblade/res/darktheme/fallback_thumb.png
failed to make icon from: /usr/lib/python3.8/site-packages/Flowblade/res/darktheme/fallback_thumb.png
failed to make icon from: /usr/lib/python3.8/site-packages/Flowblade/res/darktheme/fallback_thumb.png
failed to make icon from: /usr/lib/python3.8/site-packages/Flowblade/res/darktheme/fallback_thumb.png
failed to make icon from: /usr/lib/python3.8/site-packages/Flowblade/res/darktheme/fallback_thumb.png
failed to make icon from: /usr/lib/python3.8/site-packages/Flowblade/res/darktheme/fallback_thumb.png
failed to make icon from: /usr/lib/python3.8/site-packages/Flowblade/res/darktheme/fallback_thumb.png
failed to make icon from: /usr/lib/python3.8/site-packages/Flowblade/res/darktheme/fallback_thumb.png
failed to make icon from: /usr/lib/python3.8/site-packages/Flowblade/res/darktheme/fallback_thumb.png
failed to make icon from: /usr/lib/python3.8/site-packages/Flowblade/res/darktheme/fallback_thumb.png
failed to make icon from: /usr/lib/python3.8/site-packages/Flowblade/res/darktheme/fallback_thumb.png
failed to make icon from: /usr/lib/python3.8/site-packages/Flowblade/res/darktheme/fallback_thumb.png
failed to make icon from: /usr/lib/python3.8/site-packages/Flowblade/res/darktheme/fallback_thumb.png
failed to make icon from: /usr/lib/python3.8/site-packages/Flowblade/res/darktheme/fallback_thumb.png
failed to make icon from: /usr/lib/python3.8/site-packages/Flowblade/res/darktheme/fallback_thumb.png
failed to make icon from: /usr/lib/python3.8/site-packages/Flowblade/res/darktheme/fallback_thumb.png
failed to make icon from: /usr/lib/python3.8/site-packages/Flowblade/res/darktheme/fallback_thumb.png
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/app/share/flowblade/Flowblade/projectaction.py", line 130, in run
    project = persistance.load_project(self.filename)
  File "/app/share/flowblade/Flowblade/persistance.py", line 500, in load_project
    media_file.create_icon()
  File "/app/share/flowblade/Flowblade/containerclip.py", line 387, in create_icon
    self.icon = action_object.load_icon()
  File "/app/share/flowblade/Flowblade/containeractions.py", line 423, in load_icon
    return self._build_icon(self.get_container_thumbnail_path())
  File "/app/share/flowblade/Flowblade/containeractions.py", line 412, in _build_icon
    cr, surface = _create_image_surface(icon_path)
  File "/app/share/flowblade/Flowblade/containeractions.py", line 132, in _create_image_surface
    icon = cairo.ImageSurface.create_from_png(icon_path)
cairo.Error: file not found
```

**Comment by jliljebl** [comment]
Okay, this different then the fixed previous one, will investigate.

**Comment by Mq89** [comment]
Thank you. If I can be of further help, just let me know.

**Comment by jliljebl** [comment]
Ok, for some reason the container clip media item icon was missing and that crashed loading project. Don't know why icon was missing, but I made the loading code handle missing container clip icons, that fixes this issue.
