### ISSUE TITLE
high-dpi resource missing

### ISSUE THREAD

**Issue by con-cso** [jliljebl/flowblade#923]
flowblade 2.4.0 does not start on kubuntu 20.04 after changing some preferences

1. installed flowblade via apt
2. started once, messed with preferences
3. closing preferences prompted me to restart
4. since closing the app, it won't start again (see full traceback below)

Seems like `/usr/share/flowblade/Flowblade/res/darktheme/compositor_icon@2.png` is missing in the distribution.
A crude fix was to comment out the lines in `guiutils.py` that append the "@2" modifier to the filename.
```~$ flowblade 
FLOWBLADE MOVIE EDITOR 2.4
--------------------------
Launch script dir: /usr/bin
Running from installation...
modules path: /usr/share/flowblade/Flowblade
MLT found, version: 6.20.0
numpy version: 1.17.4
Application version: 2.4.0
OS: Ubuntu 20.04.1 LTS
Python 3.8.5 (default, Jul 28 2020, 12:59:40) 
[GCC 9.3.0]
GTK+ version: 3.24.20
XDG user data exists.
Locale: de_DE
Translations at /usr/share/locale were not found, using program root directory translations.
Use OS locale language.
Valid shortcut files found: ['flowblade.xml', 'premiere.xml']
Keyboard shortcuts file: flowblade.xml
Loading shortcuts: Flowblade
Gtk version is 3.24.20, Flowblade theme is available.
Using Full Screen size for layout: 3840 x 1200
Small height: False
Small width: False
Detecting environment...
---
video_codecs:
  - a64multi
  - a64multi5
  - alias_pix
  - amv
  - apng
  - asv1
  - asv2
  - avrp
  - avui
  - ayuv
  - bmp
  - cinepak
  - cljr
  - dnxhd
  - dpx
  - dvvideo
  - ffv1
  - ffvhuff
  - fits
  - flashsv
  - flashsv2
  - flv
  - gif
  - h261
  - h263
  - h263p
  - hap
  - huffyuv
  - jpeg2000
  - jpegls
  - ljpeg
  - magicyuv
  - mjpeg
  - mpeg1video
  - mpeg2video
  - mpeg4
  - msmpeg4v2
  - msmpeg4
  - msvideo1
  - pam
  - pbm
  - pcx
  - pgm
  - pgmyuv
  - png
  - ppm
  - prores
  - prores_aw
  - prores_ks
  - qtrle
  - r10k
  - r210
  - rawvideo
  - roqvideo
  - rv10
  - rv20
  - sgi
  - snow
  - sunrast
  - svq1
  - targa
  - tiff
  - utvideo
  - v210
  - v308
  - v408
  - v410
  - vc2
  - wrapped_avframe
  - wmv1
  - wmv2
  - xbm
  - xface
  - xwd
  - y41p
  - yuv4
  - zlib
  - zmbv
  - libaom-av1
  - libopenjpeg
  - libtheora
  - libvpx
  - libvpx-vp9
  - libwebp_anim
  - libwebp
  - libx264
  - libx264rgb
  - libx265
  - libxvid
  - h263_v4l2m2m
  - h264_nvenc
  - h264_omx
  - h264_v4l2m2m
  - h264_vaapi
  - nvenc
  - nvenc_h264
  - nvenc_hevc
  - hevc_nvenc
  - hevc_v4l2m2m
  - hevc_vaapi
  - mjpeg_vaapi
  - mpeg2_vaapi
  - mpeg4_v4l2m2m
  - vp8_v4l2m2m
  - vp8_vaapi
  - vp9_vaapi
...
---
audio_codecs:
  - comfortnoise
  - s302m
  - aac
  - ac3
  - ac3_fixed
  - alac
  - aptx
  - aptx_hd
  - dca
  - eac3
  - flac
  - g723_1
  - mlp
  - mp2
  - mp2fixed
  - nellymoser
  - opus
  - real_144
  - sbc
  - sonic
  - sonicls
  - truehd
  - tta
  - vorbis
  - wavpack
  - wmav1
  - wmav2
  - pcm_alaw
  - pcm_dvd
  - pcm_f32be
  - pcm_f32le
  - pcm_f64be
  - pcm_f64le
  - pcm_mulaw
  - pcm_s8
  - pcm_s8_planar
  - pcm_s16be
  - pcm_s16be_planar
  - pcm_s16le
  - pcm_s16le_planar
  - pcm_s24be
  - pcm_s24daud
  - pcm_s24le
  - pcm_s24le_planar
  - pcm_s32be
  - pcm_s32le
  - pcm_s32le_planar
  - pcm_s64be
  - pcm_s64le
  - pcm_u8
  - pcm_u16be
  - pcm_u16le
  - pcm_u24be
  - pcm_u24le
  - pcm_u32be
  - pcm_u32le
  - pcm_vidc
  - roq_dpcm
  - adpcm_adx
  - g722
  - g726
  - g726le
  - adpcm_ima_qt
  - adpcm_ima_wav
  - adpcm_ms
  - adpcm_swf
  - adpcm_yamaha
  - libcodec2
  - libgsm
  - libgsm_ms
  - libmp3lame
  - libopus
  - libshine
  - libspeex
  - libtwolame
  - libvorbis
  - libwavpack
...
---
formats:
  - a64
  - ac3
  - adts
  - adx
  - aiff
  - amr
  - apng
  - aptx
  - aptx_hd
  - asf
  - ass
  - ast
  - asf_stream
  - au
  - avi
  - avm2
  - avs2
  - bit
  - caf
  - cavsvideo
  - codec2
  - codec2raw
  - crc
  - dash
  - data
  - daud
  - dirac
  - dnxhd
  - dts
  - dv
  - eac3
  - f4v
  - ffmetadata
  - fifo
  - fifo_test
  - filmstrip
  - fits
  - flac
  - flv
  - framecrc
  - framehash
  - framemd5
  - g722
  - g723_1
  - g726
  - g726le
  - gif
  - gsm
  - gxf
  - h261
  - h263
  - h264
  - hash
  - hds
  - hevc
  - hls
  - ico
  - ilbc
  - image2
  - image2pipe
  - ipod
  - ircam
  - ismv
  - ivf
  - jacosub
  - latm
  - lrc
  - m4v
  - md5
  - matroska
  - matroska
  - microdvd
  - mjpeg
  - mlp
  - mmf
  - mov
  - mp2
  - mp3
  - mp4
  - mpeg
  - vcd
  - mpeg1video
  - dvd
  - svcd
  - mpeg2video
  - vob
  - mpegts
  - mpjpeg
  - mxf
  - mxf_d10
  - mxf_opatom
  - null
  - nut
  - oga
  - ogg
  - ogv
  - oma
  - opus
  - alaw
  - mulaw
  - vidc
  - f64be
  - f64le
  - f32be
  - f32le
  - s32be
  - s32le
  - s24be
  - s24le
  - s16be
  - s16le
  - s8
  - u32be
  - u32le
  - u24be
  - u24le
  - u16be
  - u16le
  - u8
  - psp
  - rawvideo
  - rm
  - roq
  - rso
  - rtp
  - rtp_mpegts
  - rtsp
  - sap
  - sbc
  - scc
  - film_cpk
  - segment
  - stream_segment,ssegment
  - singlejpeg
  - smjpeg
  - smoothstreaming
  - sox
  - spx
  - spdif
  - srt
  - sup
  - swf
  - tee
  - 3g2
  - 3gp
  - mkvtimestamp_v2
  - truehd
  - tta
  - uncodedframecrc
  - vc1
  - vc1test
  - voc
  - w64
  - wav
  - webm
  - webm_dash_manifest
  - webm_chunk
  - webp
  - webvtt
  - wtv
  - wv
  - yuv4mpegpipe
  - chromaprint
  - alsa
  - caca
  - fbdev
  - opengl
  - oss
  - pulse
  - sdl,sdl2
  - sndio
  - video4linux2,v4l2
  - xv
...
MLT detection succeeded, 173 formats, 106 video codecs and 77 audio codecs found.
602 MLT services found.
Loading render profiles...
Loading filters...
Brightness dropped, MLT version too high for this filter.
Brightness Keyframed dropped, MLT version too high for this filter.
Loading transitions...
RGB Adjustment dropped for Color Adjustment
Hue dropped for Color Adjustment
Gamma dropped for Lift Gain Gamma
G'MIC found
Player initialized with profile:  HD 1080p 60 fps
Traceback (most recent call last):
  File "/usr/bin/flowblade", line 93, in <module>
    app.main(modules_path)
  File "/usr/share/flowblade/Flowblade/app.py", line 276, in main
    create_gui()
  File "/usr/share/flowblade/Flowblade/app.py", line 431, in create_gui
    tlinewidgets.load_icons()
  File "/usr/share/flowblade/Flowblade/tlinewidgets.py", line 347, in load_icons
    COMPOSITOR_ICON = guiutils.get_cairo_image("compositor_icon")
  File "/usr/share/flowblade/Flowblade/guiutils.py", line 165, in get_cairo_image
    return cairo.ImageSurface.create_from_png(respaths.IMAGE_PATH + img_name + suffix)
cairo.Error: file not found
```

**Comment by dvdlvr** [comment]
This should obviously be fixed in distro but a better fix is to copy the icon from the default theme to the darktheme. No need to change the code.

**Comment by dvdlvr** [comment]
This was fixed in a later version.
Try installing Flowblade from the repository.
Missing @2 icons no longer make the program crash - they will just display the original sized icon.

**Comment by JimBobK** [comment]
I am joining this issue cause I am having somewhat the same issues after upgrading to 20.04 also. After re-installs and making sure all support packages are on my system, when Flowblade starts up, from the Help/environments section, it only shows 4 codecs operational. Likewise the render window only has 4 codecs that can be used. I have repeatedly toggled options on Preference window without any luck. Attached is a log file from CLI startup, along with a screen shot of the  environment section I am talking about.   Note: FFMPEG -codecs shows the same list as the log file does. Waiting for the Wizard to reply.
[flodblade_log.txt](https://github.com/jliljebl/flowblade/files/5692085/flodblade_log.txt)
![Screenshot from 2020-12-14 14-31-31](https://user-images.githubusercontent.com/76016627/102146346-a0f02b00-3e1d-11eb-9f86-697a506da9d3.png)

**Comment by jliljebl** [comment]
@JimBobK 

On my system I get:

```bash
  - adpcm_ima_qt
  - adpcm_ima_ssi
  - adpcm_ima_wav
  - adpcm_ms
  - adpcm_swf
  - adpcm_yamaha
  - libcodec2
  - libgsm
  - libgsm_ms
  - libmp3lame
  - libopus
  - libshine
  - libspeex
  - libtwolame
  - libvorbis
  - libwavpack
...
```

So libmp3lame, libtwolame are present on my system. I looked at your printout and those codecs are missing. This is an issue with your system and unfortunately I cannot further help, maybe contact distro mainters for help.

**Comment by jliljebl** [comment]
This has been fixed.
