### ISSUE TITLE
Keyboard shortcuts are not working

### ISSUE THREAD

**Issue by lillemets** [jliljebl/flowblade#948]
When I press any shortcut in Flowblade, nothing happens. When attempting to access `Edit > Keyboard Shortcuts`, the following is displayed on the terminal emulator where I run Flowblade from. Still, nothing happens in the app itself.

```
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/Flowblade/editorwindow.py", line 287, in <lambda>
    ('KeyboardShortcuts', None, _('Keyboard Shortcuts'), None, None, lambda a:dialogs.keyboard_shortcuts_dialog(self.window, workflow.get_tline_tool_working_set, menuactions.keyboard_shortcuts_callback)),
  File "/usr/lib/python3.9/site-packages/Flowblade/dialogs.py", line 1408, in keyboard_shortcuts_dialog
    diff_data.set_text(shortcuts.get_diff_to_defaults(editorpersistance.prefs.shortcuts))
  File "/usr/lib/python3.9/site-packages/Flowblade/shortcuts.py", line 170, in get_diff_to_defaults
    key_name_test, action_name = get_shortcut_info(test_root, code)
  File "/usr/lib/python3.9/site-packages/Flowblade/shortcuts.py", line 146, in get_shortcut_info
    events = root.getiterator('event')
AttributeError: 'xml.etree.ElementTree.Element' object has no attribute 'getiterator'
```

Below is info on the environment I'm running Flowblade in.

```
FLOWBLADE MOVIE EDITOR 2.6.1
----------------------------
Launch script dir: /usr/bin
Running from installation...
modules path: /usr/lib/python3.9/site-packages/Flowblade
MLT found, version: 6.24.0
numpy version: 1.19.4
Application version: 2.6.1
OS: Arch Linux
Python 3.9.1 (default, Dec 13 2020, 11:55:53) 
[GCC 10.2.0]
GTK+ version: 3.24.24
XDG user data exists.
Locale: en_US
Translations at /usr/share/locale were not found, using program root directory translations.
Use OS locale language.
Valid shortcut files found: ['flowblade.xml', 'premiere.xml']
Keyboard shortcuts file: flowblade.xml
Loading shortcuts: Flowblade
Error opening shortcuts file:flowblade.xml
Gtk version is 3.24.24, Flowblade theme is available.
Using Full Screen size for layout: 2560 x 1440
Small height: False
Small width: False
```

**Comment by lillemets** [comment]
This can be fixed by changing `getiterator` to `iter` in *shortcuts.py*.

**Comment by jliljebl** [comment]
This has been fixed in repo: https://github.com/jliljebl/flowblade/commit/5467759cb1559fb05a0c3a7a28aaa0a54044d1db
