### ISSUE TITLE
Version 2.8 doesn't show up when started in KDE

### ISSUE THREAD

**Issue by martinvlk** [jliljebl/flowblade#987]
Please include the following information.
1) Flowblade version (Help->About): 2.8
2) MLT version (Help->Runtime Environment): 6.20.0
3) Your distribution (Ubuntu, Debian, Mint etc.): KUbuntu (Focal)
4) If possible, try to provide step-by-step instructions on how to reproduce the issue. From developer point of view this is the easieast way to understand what is happening.: just start it

```
FLOWBLADE MOVIE EDITOR 2.8
--------------------------
Launch script dir: /usr/bin
Running from installation...
modules path: /usr/share/flowblade/Flowblade
MLT found, version: 6.20.0
numpy version: 1.17.4
Application version: 2.8.0
OS: Ubuntu 20.04.2 LTS
Python 3.8.5 (default, Jul 28 2020, 12:59:40) 
[GCC 9.3.0]
GTK+ version: 3.24.20
XDG user data exists.
Locale: cs_CZ
Translations at /usr/share/locale were not found, using program root directory translations.
Force use English.
Valid shortcut files found: ['flowblade.xml', 'premiere.xml']
Keyboard shortcuts file: flowblade.xml
Using Full Screen size for layout: 1920 x 1080
Small height: False
Small width: False
no more csLADSPA plugins
Detecting environment...
---
video_codecs:
  - a64multi
  - a64multi5
  - alias_pix
  - amv
  - apng
  - asv1
  - asv2
  - avrp
  - avui
  - ayuv
  - bmp
  - cinepak
  - cljr
  - dnxhd
  - dpx
  - dvvideo
  - ffv1
  - ffvhuff
  - fits
  - flashsv
  - flashsv2
  - flv
  - gif
  - h261
  - h263
  - h263p
  - hap
  - huffyuv
  - jpeg2000
  - jpegls
  - ljpeg
  - magicyuv
  - mjpeg
  - mpeg1video
  - mpeg2video
  - mpeg4
  - msmpeg4v2
  - msmpeg4
  - msvideo1
  - pam
  - pbm
  - pcx
  - pgm
  - pgmyuv
  - png
  - ppm
  - prores
  - prores_aw
  - prores_ks
  - qtrle
  - r10k
  - r210
  - rawvideo
  - roqvideo
  - rv10
  - rv20
  - sgi
  - snow
  - sunrast
  - svq1
  - targa
  - tiff
  - utvideo
  - v210
  - v308
  - v408
  - v410
  - vc2
  - wrapped_avframe
  - wmv1
  - wmv2
  - xbm
  - xface
  - xwd
  - y41p
  - yuv4
  - zlib
  - zmbv
  - libaom-av1
  - libopenjpeg
  - libtheora
  - libvpx
  - libvpx-vp9
  - libwebp_anim
  - libwebp
  - libx264
  - libx264rgb
  - libx265
  - libxvid
  - h263_v4l2m2m
  - h264_nvenc
  - h264_omx
  - h264_v4l2m2m
  - h264_vaapi
  - nvenc
  - nvenc_h264
  - nvenc_hevc
  - hevc_nvenc
  - hevc_v4l2m2m
  - hevc_vaapi
  - mjpeg_vaapi
  - mpeg2_vaapi
  - mpeg4_v4l2m2m
  - vp8_v4l2m2m
  - vp8_vaapi
  - vp9_vaapi
...
---
audio_codecs:
  - comfortnoise
  - s302m
  - aac
  - ac3
  - ac3_fixed
  - alac
  - aptx
  - aptx_hd
  - dca
  - eac3
  - flac
  - g723_1
  - mlp
  - mp2
  - mp2fixed
  - nellymoser
  - opus
  - real_144
  - sbc
  - sonic
  - sonicls
  - truehd
  - tta
  - vorbis
  - wavpack
  - wmav1
  - wmav2
  - pcm_alaw
  - pcm_dvd
  - pcm_f32be
  - pcm_f32le
  - pcm_f64be
  - pcm_f64le
  - pcm_mulaw
  - pcm_s8
  - pcm_s8_planar
  - pcm_s16be
  - pcm_s16be_planar
  - pcm_s16le
  - pcm_s16le_planar
  - pcm_s24be
  - pcm_s24daud
  - pcm_s24le
  - pcm_s24le_planar
  - pcm_s32be
  - pcm_s32le
  - pcm_s32le_planar
  - pcm_s64be
  - pcm_s64le
  - pcm_u8
  - pcm_u16be
  - pcm_u16le
  - pcm_u24be
  - pcm_u24le
  - pcm_u32be
  - pcm_u32le
  - pcm_vidc
  - roq_dpcm
  - adpcm_adx
  - g722
  - g726
  - g726le
  - adpcm_ima_qt
  - adpcm_ima_wav
  - adpcm_ms
  - adpcm_swf
  - adpcm_yamaha
  - libcodec2
  - libgsm
  - libgsm_ms
  - libmp3lame
  - libopus
  - libshine
  - libspeex
  - libtwolame
  - libvorbis
  - libwavpack
...
---
formats:
  - a64
  - ac3
  - adts
  - adx
  - aiff
  - amr
  - apng
  - aptx
  - aptx_hd
  - asf
  - ass
  - ast
  - asf_stream
  - au
  - avi
  - avm2
  - avs2
  - bit
  - caf
  - cavsvideo
  - codec2
  - codec2raw
  - crc
  - dash
  - data
  - daud
  - dirac
  - dnxhd
  - dts
  - dv
  - eac3
  - f4v
  - ffmetadata
  - fifo
  - fifo_test
  - filmstrip
  - fits
  - flac
  - flv
  - framecrc
  - framehash
  - framemd5
  - g722
  - g723_1
  - g726
  - g726le
  - gif
  - gsm
  - gxf
  - h261
  - h263
  - h264
  - hash
  - hds
  - hevc
  - hls
  - ico
  - ilbc
  - image2
  - image2pipe
  - ipod
  - ircam
  - ismv
  - ivf
  - jacosub
  - latm
  - lrc
  - m4v
  - md5
  - matroska
  - matroska
  - microdvd
  - mjpeg
  - mlp
  - mmf
  - mov
  - mp2
  - mp3
  - mp4
  - mpeg
  - vcd
  - mpeg1video
  - dvd
  - svcd
  - mpeg2video
  - vob
  - mpegts
  - mpjpeg
  - mxf
  - mxf_d10
  - mxf_opatom
  - null
  - nut
  - oga
  - ogg
  - ogv
  - oma
  - opus
  - alaw
  - mulaw
  - vidc
  - f64be
  - f64le
  - f32be
  - f32le
  - s32be
  - s32le
  - s24be
  - s24le
  - s16be
  - s16le
  - s8
  - u32be
  - u32le
  - u24be
  - u24le
  - u16be
  - u16le
  - u8
  - psp
  - rawvideo
  - rm
  - roq
  - rso
  - rtp
  - rtp_mpegts
  - rtsp
  - sap
  - sbc
  - scc
  - film_cpk
  - segment
  - stream_segment,ssegment
  - singlejpeg
  - smjpeg
  - smoothstreaming
  - sox
  - spx
  - spdif
  - srt
  - sup
  - swf
  - tee
  - 3g2
  - 3gp
  - mkvtimestamp_v2
  - truehd
  - tta
  - uncodedframecrc
  - vc1
  - vc1test
  - voc
  - w64
  - wav
  - webm
  - webm_dash_manifest
  - webm_chunk
  - webp
  - webvtt
  - wtv
  - wv
  - yuv4mpegpipe
  - chromaprint
  - alsa
  - caca
  - fbdev
  - opengl
  - oss
  - pulse
  - sdl,sdl2
  - sndio
  - video4linux2,v4l2
  - xv
...
MLT detection succeeded, 173 formats, 106 video codecs and 77 audio codecs found.
921 MLT services found.
Loading render profiles...
Loading filters...
Loading transitions...
RGB Adjustment dropped for Color Adjustment
Hue dropped for Color Adjustment
Gamma dropped for Lift Gain Gamma
G'MIC found
Player initialized with profile:  Pixel video
Traceback (most recent call last):
  File "/usr/bin/flowblade", line 93, in <module>
    app.main(modules_path)
  File "/usr/share/flowblade/Flowblade/app.py", line 307, in main
    create_gui()
  File "/usr/share/flowblade/Flowblade/app.py", line 487, in create_gui
    editor_window = editorwindow.EditorWindow()
  File "/usr/share/flowblade/Flowblade/editorwindow.py", line 166, in __init__
    self._init_view_menu(self.ui.get_widget('/MenuBar/ViewMenu'))
  File "/usr/share/flowblade/Flowblade/editorwindow.py", line 1081, in _init_view_menu
    panel_positions_menu_item = editorlayout.get_panel_positions_menu_item()
  File "/usr/share/flowblade/Flowblade/editorlayout.py", line 363, in get_panel_positions_menu_item
    project_panel_menu = _get_position_selection_menu(appconsts.PANEL_PROJECT)
  File "/usr/share/flowblade/Flowblade/editorlayout.py", line 419, in _get_position_selection_menu
    current_position = _get_panel_position(panel_id)
  File "/usr/share/flowblade/Flowblade/editorlayout.py", line 214, in _get_panel_position
    return _panel_positions[panel]
KeyError: 6
```

**Comment by martinvlk** [comment]
![image](https://user-images.githubusercontent.com/4638575/107699750-ce8b1080-6cb6-11eb-8f77-eeceb1c823ae.png)

**Comment by jose1711** [comment]
I don't think this is related to DE/WM used but since you mention 'KDE' specifically.. have you tried any other WMs (e. g. xfce or openbox)?

**Comment by jliljebl** [comment]
No idea why this is happening, based on terminal output this should fail on every system and it obviously does no here. Leaving this open for more info.

**Comment by DroWnThePoor** [comment]
I'm experiencing the exact same thing on Ubuntu 18.04 with the Flatpak version.
I upgraded to 2.8 and noticed it would not run, and then decided to manually run it via flatpak in the terminal.
I think I had the same problem with 2.6.2 and ended up reverting to the previous version.
I use this program a lot so I'm very interested in solving this issue.

**Comment by jliljebl** [comment]
Alright, I'll try to get reproduction somehow but I did the install tests on Ubuntu 20.04 and Linux Mint 20.

**Comment by martinvlk** [comment]
I'll try with a different WM this evening. Had a project to finish 
before I could fiddle with my install.

MV

Dne 16. 02. 21 v 13:49 jliljebl napsal(a):

**Comment by jliljebl** [comment]
Ok, I found it. 

If the preference "Top row layout:" in Preferences View Tab is set to "Always use 2 panels" this happens. I never use the pref, didn't remember it, didn't test against it, this the way the f.....g regressions happen. This is why they have teams of people testing stuff before release. Also why adding prefs too easily is not good, I may have quilty of this.

Easy fix, I'll be pushing fixes soon.

**Comment by martinvlk** [comment]
Excellent, many thanks!

Martin

Dne 16. 02. 21 v 14:44 jliljebl napsal(a):

**Comment by jliljebl** [comment]
Pushed the Flatpak fix, it is building.

**Comment by jliljebl** [comment]
@martinvlk The 2.8.0.1 Release .deb file is now available, could you install and verify the fix?

**Comment by martinvlk** [comment]
Installed the latest version from flathub and it now starts fine - many thanks!

MV
